### ISSUE TITLE
Map asset import bug?

### ISSUE THREAD

**Issue by shiron7** [REDxEYE/SourceIO#113]
heyoss, im trying to get a map imported, the geometry imports just fine, but when i try importing the assets, they get messed up like the picture, no matter if i do it manually or in multiple selection, have  done ssomething wrong or is it a bug? 
![image](https://user-images.githubusercontent.com/56375507/133677481-f3d1fc5b-5d2e-443e-87e3-3fa4ba17ca43.png)

i wil attach the console log, there was more but thats all i could copy
[log.txt](https://github.com/REDxEYE/SourceIO/files/7180624/log.txt)

**Comment by REDxEYE** [comment]
Fixed in recent commits
