### ISSUE TITLE
Giving some errors

### ISSUE THREAD

**Issue by LeonSKenny** [REDxEYE/SourceIO#118]
[](url)Hello. 
Recently I wanted to import a map from SFM into Blender and downloaded Source IO-Master
After doing the steps and saving I tried to import but this shows up
It even gives the same error for models 
![bandicam 2021-12-08 22-20-43-104](https://user-images.githubusercontent.com/95774739/145269676-0e6433bd-4291-4960-a092-441ec9141208.jpg)

**Comment by REDxEYE** [comment]
Okay, i know what's causing that, will fix in next commit

**Comment by REDxEYE** [comment]
@LeonSKenny Fixed

**Comment by LeonSKenny** [comment]
Thank you so much!
