### ISSUE TITLE
Eye pink

### ISSUE THREAD

**Issue by Eltorus19** [REDxEYE/SourceIO#119]
Everytime I import a sfm model, the eyes gets pink textures as the nodes has not output nodes. How can fix or works for the eyes in general?
![Captura de pantalla (1149)](https://user-images.githubusercontent.com/96163736/146129002-39888e60-03d3-4d1e-bbad-f4dd12ff52ab.png)
?

**Comment by Eltorus19** [comment]
Everytime I import a sfm model, the eyes gets pink textures as the nodes has not output nodes. How can fix or works for the eyes in general?

**Comment by Eltorus19** [comment]
Everytime I import a sfm model, the eyes gets pink textures as the nodes has not output nodes. How can fix or works for the eyes in general?

**Comment by REDxEYE** [comment]
Eyes shaders are not supported, you need to re-create materials for eyes
