### ISSUE TITLE
Recent Dota 2 update breaks some models on import

### ISSUE THREAD

**Issue by maxxysfm** [REDxEYE/SourceIO#120]
Hello! I was using the latest branch when I ecountered this issue.
I was trying to import some of the new models released with the recent Dota 2 update.
![Picture](https://user-images.githubusercontent.com/23436653/146235674-ff684fd1-b8a5-4a92-a414-7bd1b91121bb.png)
It seems to be running into some errors whenever I'm trying to open the **drow_arcana.vmdl_c**
[drow_arcana.zip](https://github.com/REDxEYE/SourceIO/files/7721547/drow_arcana.zip)
but generally this seems to apply to any meshes that use shapekeys.

There is also a model that **previously was working**, but **now it only imports the armature** (no meshes imported, no errors):
[legion_commander.zip](https://github.com/REDxEYE/SourceIO/files/7721584/legion_commander.zip)

Importing models without blendmorphs seems to work however (for example **drow_arcana_debut_arrow.vmdl_c**)

**Comment by REDxEYE** [comment]
Both model load fine now, please try to use 4.0 version

**Comment by maxxysfm** [comment]
There seems to be some other issue now. I tested it with a freshly installed Blender and there is a missing module error now:
```
File "C:\Users\[]\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\SourceIO-master\library\source2\utils\binary_keyvalue.py", line 5, in <module>
    from SourceIO.library.utils.byte_io_mdl import ByteIO
ModuleNotFoundError: No module named 'SourceIO'
```

**Comment by REDxEYE** [comment]
My bad, forgot to update imports

**Comment by REDxEYE** [comment]
Please re-download addon

**Comment by maxxysfm** [comment]
> Please re-download addon

Thank you so much! It imports the models perfectly fine as well!
