### ISSUE TITLE
If some parts of the map are not loading into Blender, but the map works fine in SFM 1, how do I fix this?

### ISSUE THREAD

**Issue by useahname** [REDxEYE/SourceIO#121]
Hi, thanks first of all for the fantastic plug-in, it's been working great for models. Switching from SFM to Blender couldn't be much easier honestly, especially once all the little issues are ironed out.

Long story short I've tried to import a SFM bsp map into Blender but the textures are missing (here's the console information)
[Source IO errors.txt](https://github.com/REDxEYE/SourceIO/files/7781229/Source.IO.errors.txt)
 
and here is the map file itself, there are a few versions (clean, messy, no light, lights etc), this one is called "sfm_apartment_grungy.bsp":
 https://sfmlab.com/project/26891/
 
 the result is it looks like this:
 
![Screenshot (3038)](https://user-images.githubusercontent.com/96742616/147496349-2c02ee70-8ec9-4983-904f-78259f8f3261.png)

but in SFM 1 it looks like this:

![Screenshot (3037)](https://user-images.githubusercontent.com/96742616/147496370-349c0989-bc15-4137-a672-c76c4e3395a6.png)

 
I've followed the tutorial on the SFMLab Youtube channel, and read the comments for similar issues, but the solution was basically make sure you have the textures, which I do cause they're included and working in SFM.

If you know what I can do to fix it I'd be grateful!

Thanks!

**Comment by REDxEYE** [comment]
Hello, make sure you placed map file into SFM maps folder, ex: usermod/maps
It won't work if you try to load it from anywhere else, because SIO need to detect source game (SFM in your case) and mount all it's content folders (ex: usermod, workshop and etc)
And in case of this map, make sure you've installed bundled materials correctly

**Comment by useahname** [comment]
> Hello, make sure you placed map file into SFM maps folder, ex: usermod/maps It won't work if you try to load it from anywhere else, because SIO need to detect source game (SFM in your case) and mount all it's content folders (ex: usermod, workshop and etc) And in case of this map, make sure you've installed bundled materials correctly

Whoops, thanks very much, it worked perfectly lol. My first feeling with something is to make a backup and load from that instead in case the importer effects the original files. And thanks very much for responding so quickly!

**Comment by REDxEYE** [comment]
All files are open in read-only mode. SIO does not write/edit any files
