### ISSUE TITLE
Hair and Eyelashes not displaying properly.

### ISSUE THREAD

**Issue by dsguffey** [REDxEYE/SourceIO#122]
First of all, thank you so much for making this addon! It's the best thing I've been able to find for importing source files to Blender. I am having one reoccurring problem though. In a lot of models, the hair and eyelashes are not textured properly. I thought the problem might involve my alpha settings, so I checked screen space refractions in Blender's evee, but it didn't seem to help. The custom shader doesn't seem to have transmission settings, so I'm not sure what else to do. Here's a picture to give you an idea what's going on. I appreciate your help.

![Elizabeth Canon Capture](https://user-images.githubusercontent.com/65681495/148693704-6862d08d-122c-45ea-a8c0-aa99a1cf48f9.JPG)

**Comment by REDxEYE** [comment]
Source materials come is so many different configurations, it's impossible to account for everything, you can manually connect texture alpha to Alpha-test node

**Comment by dsguffey** [comment]
OK, that's fair. Do you know of any good forums to find out exactly what source files are and how they convert to Blender? I ran into a _i file recently and I'm not sure what that is. I've tried my own searches, but no obviously correct answer is coming up.

**Comment by REDxEYE** [comment]
There is no standard naming convention on texture names. The only way is to manually analyze material and figure out how it used in source engine and remap it to blender

**Comment by dsguffey** [comment]
OK, thanks
