### ISSUE TITLE
SourceIO won't enable on macOS after install

### ISSUE THREAD

**Issue by ddomino007** [REDxEYE/SourceIO#127]
hey, it's me again xD
the same issue as the one I reported a big while ago
it was fixed back then and now it's back
![image](https://user-images.githubusercontent.com/23064460/156920805-f2518aa8-28ef-47d5-a755-752c5c9bf288.png)
x86-64 2.8, arm64 2.8
arm64 3.0, arm64 3.1
^
|
all exhibit this issue

**Comment by REDxEYE** [comment]
I'll add macos version of this library as soon as I can

**Comment by ddomino007** [comment]
I'll download the latest commit to test this and get back to you asap

**Comment by ddomino007** [comment]
still happening.
![image](https://user-images.githubusercontent.com/23064460/158057437-e96eac66-9b70-41b0-89fe-1346706945bc.png)
let me know when I can help with testing

**Comment by REDxEYE** [comment]
Post full console log

**Comment by User-444** [comment]
It won't open and i am on mac the only thing i hidden was the user name. and the thing i am showing the full console log
![Untitled drawing (2)](https://user-images.githubusercontent.com/102774895/161178669-d4099b5b-a1c7-469f-ab25-0c40075a7b17.png)

**Comment by REDxEYE** [comment]
macos not supproted right now

**Comment by Jasongamerkid14** [comment]
this is the worst addon for mac, can you fixit or i will report it.

**Comment by REDxEYE** [comment]
The addon is designed to run only on windows, other system support is provided with no warranty
