### ISSUE TITLE
Mess with shape keys

### ISSUE THREAD

**Issue by Eltorus19** [REDxEYE/SourceIO#134]
I tried everything to import with this and other addons, merge by distance after joining meshes, and still the shape keys gets fucked. Any idea how can I fix it?

![Captura de pantalla (1243)](https://user-images.githubusercontent.com/96163736/159106777-a233acec-8d82-48fb-95ca-0be0aa8436a0.png)

**Comment by REDxEYE** [comment]
This is something i don't know how to fix
