### ISSUE TITLE
Not working for 2.79

### ISSUE THREAD

**Issue by Maggi33** [REDxEYE/SourceIO#137]
AttributeError: module 'bpy.utils' has no attribute 'register_classes_factory'

I used the version for 2.8 because it was the closest but it I don't know how to fix this

![fvbaevwsEdfaes](https://user-images.githubusercontent.com/102268247/159820496-f8987308-bfd4-49f9-be13-7bdb351b278d.PNG)
.

**Comment by REDxEYE** [comment]
This addon is only for Blender 2.90-3.20
