### ISSUE TITLE
error with enabling addon

### ISSUE THREAD

**Issue by Formalspark74** [REDxEYE/SourceIO#143]
when try to enable the addon it gives me this error

![Screenshot 2022-04-16 193413](https://user-images.githubusercontent.com/103848874/163685497-5645161b-3a07-416d-8f67-6320d9ddf72a.png)

**Comment by REDxEYE** [comment]
Fixed in [1d43fd9](https://github.com/REDxEYE/SourceIO/commit/1d43fd9632d3f391a763314e55bc279aaccf7aef)
