### ISSUE TITLE
Cannot enable this addon

### ISSUE THREAD

**Issue by LemonBruh** [REDxEYE/SourceIO#144]
I love this addon, have been using it for a while
but today I upgraded from blender 2.92 to 3.1.2
even since then I can install the addon but when I go to check the box i get an error message saying

![image](https://user-images.githubusercontent.com/63004992/163685675-1b33a0d3-4eaf-4c2f-9c31-ffc360d33f78.png)

if I were to guess, maybe the addon isn't supported in later versions of blender...

if this were the case then this would be very bad because i am in the works of a tutorial of how to import SFM models into blender right now, and even though I have all the footage i need for the video, I still need to use it for various other reasons

I hope there is a simple solution for this

Thanks

**Comment by Formalspark74** [comment]
i have the same issue

**Comment by REDxEYE** [comment]
Has been fixed in last commit

**Comment by Formalspark74** [comment]
TY
