### ISSUE TITLE
Can't import models without error

### ISSUE THREAD

**Issue by LemonBruh** [REDxEYE/SourceIO#145]
Hi its me again
after installing the new version of SourceIO in 3.1.2, I clicked the check box and it worked!

![image](https://user-images.githubusercontent.com/63004992/163715674-f9131e57-a456-4ccd-a734-114066a86540.png)

Unfortunately after I clicked import and source model, it didn't work and I got a new error

![image](https://user-images.githubusercontent.com/63004992/163715729-f19e5126-82f2-496f-9a4a-cf13c13d62fb.png)

And now I cant uninstall SourceIO without getting another error, I looked in the addons folder in the blender files and it wasn't even there

please help

thanks

**Comment by ramtiawdwad** [comment]
I have the same issue

**Comment by REDxEYE** [comment]
Fixed in [b2e78bd](https://github.com/REDxEYE/SourceIO/commit/b2e78bd841ae485e6eb683d247ef93ffcee73e4f)

**Comment by ramtiawdwad** [comment]
Thanks your addon is awesome
