### ISSUE TITLE
Import Map Error with Models

### ISSUE THREAD

**Issue by Dyoh0** [REDxEYE/SourceIO#148]
Hi, I'm trying to load this map https://steamcommunity.com/sharedfiles/filedetails/?id=252027525&searchtext=forest and all of the trees and buildings and other assets show up as empties.
![error](https://user-images.githubusercontent.com/26355058/165788169-89041b94-498c-402e-911b-f8f9a2ccce7a.png)

**Comment by REDxEYE** [comment]
Please, take a look here https://github.com/REDxEYE/SourceIO/blob/master/wiki/BSP_IMPORT.md
