### ISSUE TITLE
Issue Enabling Addon

### ISSUE THREAD

**Issue by taksity** [REDxEYE/SourceIO#149]
Dear REDxEYE,

I am using Blender 3.1.2 on a Lenovo running Pop! OS 21.10, when I try installing the latest version or release of this repository I run into an issue when attempting to enable the Add-on (see screenshot provided).

![bitmap](https://user-images.githubusercontent.com/73563644/166412484-b7884b14-d37b-4cb9-97fb-4df64fcbaf87.png)

I am unsure what libpython3.8.so.1.0 is, but it looks like a shared object file related to python 3.8.

Any insight you have regarding this matter would be greatly appreciated.

Thank you for your time.

**Comment by REDxEYE** [comment]
interesting, never seen anything like that

**Comment by taksity** [comment]
Sorry to cause such a fuss. I think I've gotten the module working (see screenshot below).

![bitmap](https://user-images.githubusercontent.com/73563644/166886764-4f44ce3d-ebf9-45c3-95d8-853757a63b95.png)

The error message didn't make it clear to me, but it appears that the import call was prioritizing 'pylib.pyd' over 'pylib.so'. Taking a peek inside reveals that the .pyd file is MS/DOS formatted while the .so file is ELFx86-64 formatted.

This piqued my interest in the mechanics of Python's import system; however, I have been unable to find any clarification within the official Python documentation for how import decides 'ties' when multiple files with differing valid file extensions are found.

Unless I come across any new errors I am considering this matter resolved.

**Comment by VictorMX2307** [comment]
I installed Python 3.8 on Fedora and it worked
