### ISSUE TITLE
OSError: libtxc_dxtn.so: cannot open shared object file

### ISSUE THREAD

**Issue by 0Curtain0** [REDxEYE/SourceIO#15]
**Blender v2.80 Official Release**
**Ubuntu Linux 64bit**
**SourceIO v3.5.1**

```
Traceback (most recent call last):
  File "/home/user/Downloads/Blender/blender-2.80-linux-glibc217-x86_64/2.80/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/user/.config/blender/2.80/scripts/addons/SourceIO/__init__.py", line 15, in <module>
    from .vtf.blender_material import BlenderMaterial
  File "/home/user/.config/blender/2.80/scripts/addons/SourceIO/vtf/blender_material.py", line 5, in <module>
    from ..vtf.import_vtf import import_texture
  File "/home/user/.config/blender/2.80/scripts/addons/SourceIO/vtf/import_vtf.py", line 6, in <module>
    from ..vtf.VTFWrapper import VTFLib
  File "/home/user/.config/blender/2.80/scripts/addons/SourceIO/vtf/VTFWrapper/VTFLib.py", line 40, in <module>
    class VTFLib:
  File "/home/user/.config/blender/2.80/scripts/addons/SourceIO/vtf/VTFWrapper/VTFLib.py", line 44, in VTFLib
    vtflib_cdll = cdll.LoadLibrary(os.path.join(full_path, vtf_lib_name))
  File "/home/user/Downloads/Blender/blender-2.80-linux-glibc217-x86_64/2.80/python/lib/python3.7/ctypes/__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "/home/user/Downloads/Blender/blender-2.80-linux-glibc217-x86_64/2.80/python/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtxc_dxtn.so: cannot open shared object file: No such file or directory
```
I believe this was mentioned here https://github.com/REDxEYE/SourceIO/issues/13#issuecomment-515693422 
but I should have made it a separate issue earlier to reduce confusion.

**Comment by REDxEYE** [comment]
install libtxc-dxtn library

**Comment by 0Curtain0** [comment]
I was googling how to install libtxc-dxtn, and I came across these 2 pages:
- https://www.codeweavers.com/support/wiki/diag/missinglibtxc_dxtn
- https://wiki.winehq.org/Wine-Staging_Packaging

I am on an Ubuntu based OS (Pop!_OS 64bit). Which method or where should I go to learn how to properly install this library? 
I currently don't see libtxc_dxtn in the repositories.

If my current linux distribution is a problem, then I can try a different linux distribution, or I can stick with Crowbar + BleST.

**Comment by REDxEYE** [comment]
Use 1st link

**Comment by 0Curtain0** [comment]
I tried the 1st link and it appears that those packages no longer exist. 
Is this something that Blender requires or is it something unique to the SourceIO add-on? 
If it's a distribution problem, I may have to experiment with another.

**Comment by REDxEYE** [comment]
This is dependency of libVTFEdit

**Comment by REDxEYE** [comment]
Try instaling Mesa https://bugs.archlinux.org/task/56660

**Comment by 0Curtain0** [comment]
Won't Mesa conflict with Nvidia's closed proprietary graphics drivers on Linux? 

https://computergraphics.stackexchange.com/questions/5822/if-i-have-an-nvidia-graphics-card-on-linux-do-i-need-mesa-or-freeglut-or-anythi 

Before I try a different Linux distribution, I will try installing the Steam version of Blender 2.80.

**Comment by REDxEYE** [comment]
You can also try to build it from sourcer https://people.freedesktop.org/~cbrill/libtxc_dxtn/

**Comment by 0Curtain0** [comment]
@Ganonmaster  
Hey Ganonmaster, I don't know how much experience you have with Linux, but do you know if it's safe to install **mesa-common-dev** on a system that uses a nvidia graphics card and nvidia proprietary drivers? I need the **libtxc-dxtn** library. 

I'm just looking for a trusted package or a safe method that will install **libtxc_dxtn** or however it's spelled.

I'm using **Pop!_OS** 64bit (based on Ubuntu).

**Comment by Ganonmaster** [comment]
@0Curtain0 
The `mesa-common-dev` package can likely be installed without problem, as long as you do not change your default graphics driver to Mesa.

Installing the package on your system will also install its dependencies. In the worst case, it will also select mesa as the default graphics driver. If that happens, you might need to change this back to the right Nvidia driver.

**Comment by 0Curtain0** [comment]
**Blender v2.80 Official Release**
**Pop!_OS** 64bit (based on Ubuntu)
**SourceIO** v**3.5.1** ( 84899ac - **July 30 2019** )

Thank you @Ganonmaster and @REDxEYE 
The **mesa-common-dev** package worked with the following instructions I found here: 
- https://askubuntu.com/questions/1033209/libtxc-dxtn-libtxc-dxtni386-not-found-in-ppa-18-04-bionic 

> You can compile it from sources
> Sources are not maintained since 2 years
> The code is hosted on freedesktops git infrastructure at:
> http://cgit.freedesktop.org/~mareko/libtxc_dxtn/
> 
> Here is how to compile the libtxc-dxtn library
> Run those lines as USER

```
# required stuff
sudo apt-get install mesa-common-dev
# get source files
cd ~/
wget https://people.freedesktop.org/~cbrill/libtxc_dxtn/libtxc_dxtn-1.0.1.tar.gz
tar xvfz libtxc_dxtn-1.0.1.tar.gz
cd libtxc_dxtn-1.0.1
# start the job
./configure
make
sudo make install
# clean up sources (optional)
cd ..
rm -rf libtxc_dxtn-1.0.1 libtxc_dxtn-1.0.1.tar.gz
``` 
Then reboot computer.

Looks like MDLs and VTFs are importing correctly. 

I don't know if there are any known system side effects from installing something that is no longer being maintained. I'm wondering if there could be a legitimate reason for it not being maintained anymore...possibly a better alternative to libtxc_dxtn? 

Anyway, thank you for getting the add-on to work on Linux.

Somewhat unrelated to the libtxc_dxtn but related to Linux, the latest commit from **Sep 26, 2019** appears to have revived an old issue on Linux: 
- https://github.com/REDxEYE/SourceIO/issues/9#issuecomment-538696291

**Comment by Ganonmaster** [comment]
`libtxc_dxtn` is an old library that is being used to provide S3TC support in the Linux version of VTFLib. Since there are likely no other libraries or programs on your computer that depend on this old library, it's unlikely that it will cause side-effects.

Ideally VTFLib would be updated to implement modern libraries, but since that's not a small task, we're stuck with what we have.

**Comment by ReubenU** [comment]
After installing, still didn't work for me.

**Comment by ReubenU** [comment]
Nvm it worked the second attempt.
