### ISSUE TITLE
Importing error on linux

### ISSUE THREAD

**Issue by ZimuxNowChock** [REDxEYE/SourceIO#150]
The addon worked perfectly back when I used windows, but when I changed my pc to linux mint, I have been getting this message everytime I try to import any model.

![Screenshot at 2022-05-18 15-48-16](https://user-images.githubusercontent.com/105825005/169164280-f3c8d6d1-c8db-40d9-beed-0ef7c39653bf.png)

**Comment by ZimuxNowChock** [comment]
Now it gives me this error
![Screenshot at 2022-05-19 18-10-37](https://user-images.githubusercontent.com/105825005/169424043-58fd48f0-9855-49f9-aa69-340f9eca49fe.png)

**Comment by REDxEYE** [comment]
Take a look at #156
