### ISSUE TITLE
Viewtarget issue

### ISSUE THREAD

**Issue by Joose2005** [REDxEYE/SourceIO#152]
When importing models from SFM that have viewtargets the eye texture is replaced with pink.

I've found a solution to this is to separate the eye mesh from the model and use UV maps.

I'm putting this here so that it's easy information for people to access. 

You're welcome.

**Comment by eros71-dev** [comment]
I've found a workaround for that, you can also install another similar addon called Plumber (formerly known as io_import_vmf) https://github.com/lasa01/io_import_vmf/releases
It lets you import the eye materials without issue, and then you can just replace the pink material with the new imported one.
It also can import models, but the results aren't as clean, for example, there's no collections for the different meshes and they will have weird shading.
