### ISSUE TITLE
lost some texture of cs 1.6 bsp map

### ISSUE THREAD

**Issue by neuron42** [REDxEYE/SourceIO#154]
I download the map from this page
https://maps.cs-bg.info/maps/cs/109/
The specific problem is shown in the screenshots below
![image](https://user-images.githubusercontent.com/54159914/179155801-37535578-90d8-4134-9bc3-ddda8d816856.png)
I'm just learning blender this week, so I'm still not familiar with the operation, thank you very much for your help!

**Comment by REDxEYE** [comment]
Please attach console logs

**Comment by neuron42** [comment]
@REDxEYE i uplpad the logs here
[logs.txt](https://github.com/REDxEYE/SourceIO/files/9122052/logs.txt)

**Comment by REDxEYE** [comment]
Put map into CS1.6 game folder and try again

**Comment by neuron42** [comment]
![image](https://user-images.githubusercontent.com/54159914/179269653-aa2ad32f-359b-41b7-8a55-ac4f729dfd6f.png)
Thank you, but the material of the sky box is still not correct.Just like in the picture, the sky box is solid color
@REDxEYE
[logs.txt](https://github.com/REDxEYE/SourceIO/files/9122617/logs.txt)

**Comment by REDxEYE** [comment]
Skybox polygons have correct material. It should be blue material with "skybox" text on it. Actual skybox cubemap is not supported by SourceIO for GoldSrc engine

**Comment by neuron42** [comment]
thanx
