### ISSUE TITLE
Export fbx embed textures do not support blenderVertexLitGeneric

### ISSUE THREAD

**Issue by vvb0762** [REDxEYE/SourceIO#155]
After testing, export fbx embed textures do not support blenderVertexLitGeneric, even if the textures are already unpacked to the textures folder tga format. So we need to re-add textures one by one when importing unity or unreal. Would it be possible to support fbx embed in the future?This will save very much time, thanks!

**Comment by REDxEYE** [comment]
It's an issue with FBX plugin, nothing I can do.

**Comment by vvb0762** [comment]
But I have tried other formats such as obj, usd, glft, and other export plugins and none of them support，and Regular BSDF is successful😂

**Comment by REDxEYE** [comment]
Try disabling BVLG option, it would make sourceio generate materials only using default blender nodes

**Comment by vvb0762** [comment]
![image](https://user-images.githubusercontent.com/53254328/180600385-c7b2af45-a3c9-4d20-9c08-db473fcfbaf6.png)
WOW! It worked this time! Disabling BVLG option and using Better FBX Exporter addon, thank you!
