### ISSUE TITLE
Cannot enable addon: "ImportError: libpython3.8.so.1.0: cannot open shared object file: No such file or directory"

### ISSUE THREAD

**Issue by terrab0x** [REDxEYE/SourceIO#156]
When I try to enable the addon, I get this error:
```
Traceback (most recent call last):
  File "/usr/share/blender/3.2/scripts/modules/addon_utils.py", line 335, in enable
    mod = __import__(module_name)
  File "/home/terra/.config/blender/3.2/scripts/addons/SourceIO-master/__init__.py", line 18, in <module>
    from .blender_bindings.bindings import register, unregister
  File "/home/terra/.config/blender/3.2/scripts/addons/SourceIO-master/blender_bindings/bindings.py", line 15, in <module>
    from .operators.goldsrc_operators import (SOURCEIO_OT_GBSPImport,
  File "/home/terra/.config/blender/3.2/scripts/addons/SourceIO-master/blender_bindings/operators/goldsrc_operators.py", line 8, in <module>
    from ..goldsrc import import_model
  File "/home/terra/.config/blender/3.2/scripts/addons/SourceIO-master/blender_bindings/goldsrc/__init__.py", line 4, in <module>
    from ..goldsrc.mdl_v4.import_mdl import import_model as import_model_v4
  File "/home/terra/.config/blender/3.2/scripts/addons/SourceIO-master/blender_bindings/goldsrc/mdl_v4/import_mdl.py", line 14, in <module>
    from ...shared.model_container import GoldSrcV4ModelContainer
  File "/home/terra/.config/blender/3.2/scripts/addons/SourceIO-master/blender_bindings/shared/model_container.py", line 9, in <module>
    from ...library.source2.resource_types import ValveCompiledModel
  File "/home/terra/.config/blender/3.2/scripts/addons/SourceIO-master/library/source2/resource_types/__init__.py", line 1, in <module>
    from .resource import ValveCompiledResource
  File "/home/terra/.config/blender/3.2/scripts/addons/SourceIO-master/library/source2/resource_types/resource.py", line 3, in <module>
    from ..data_blocks.compiled_file_header import CompiledHeader, InfoBlock
  File "/home/terra/.config/blender/3.2/scripts/addons/SourceIO-master/library/source2/data_blocks/__init__.py", line 2, in <module>
    from .mrph_block import MRPH
  File "/home/terra/.config/blender/3.2/scripts/addons/SourceIO-master/library/source2/data_blocks/mrph_block.py", line 4, in <module>
    from .data_block import DATA
  File "/home/terra/.config/blender/3.2/scripts/addons/SourceIO-master/library/source2/data_blocks/data_block.py", line 2, in <module>
    from ..utils.binary_keyvalue import BinaryKeyValue
  File "/home/terra/.config/blender/3.2/scripts/addons/SourceIO-master/library/source2/utils/binary_keyvalue.py", line 8, in <module>
    from ...utils.pylib_loader import pylib
  File "/home/terra/.config/blender/3.2/scripts/addons/SourceIO-master/library/utils/pylib_loader/__init__.py", line 14, in <module>
    from .unix import pylib
ImportError: libpython3.8.so.1.0: cannot open shared object file: No such file or directory
```

OS: Arch Linux
Blender Version: 3.2
Addon Versions: 4.0.3 and master (both give the same error)

**Comment by TuxoYKT** [comment]
[pylib](https://github.com/REDxEYE/pylib) library used in the latest release and master expects Python 3.8 to be installed.

Managed to make this work in Ubuntu 22.04 with Python 3.10 installed by compiling [pylib](https://github.com/REDxEYE/pylib) on my system and replacing packaged pylib.so with my compiled one. Seems like you'll have to do this every time you update Python in your system.

![image](https://user-images.githubusercontent.com/6498761/183470224-91ce7db1-a9d2-498c-a7e3-8e22f524ac75.png)

**Comment by REDxEYE** [comment]
This issue is only reproducible on Linux, windows build works with any python>=3.7, maybe something wrong with my CMake project

**Comment by AliaKhin** [comment]
I have same problem on Arch based Linux. Can't make it work and have many even unrelated python packages installed

**Comment by REDxEYE** [comment]
??

**Comment by AliaKhin** [comment]
![image](https://user-images.githubusercontent.com/105072755/183770933-0f132dad-8c3b-48f0-aa77-bfc0925c1268.png)
I have this error when I am trying to install the addon.
I tried to install it from zip and tried to unzip it directly in /home/yupc/.config/blender/3.2/scripts/addons.
Same error in both cases

**Comment by TuxoYKT** [comment]
Guess I'll write the commands I used to make this work.
```
curl -fLO https://github.com/REDxEYE/SourceIO/archive/refs/heads/master.zip
unzip master.zip
git clone https://github.com/REDxEYE/pylib.git --recurse-submodules 
cd pylib/src
cmake ..
make
mv pylib.so ../../SourceIO-master/library/utils/pylib_loader/unix/pylib.so
cd ../..
zip -r SourceIO.zip SourceIO-master
```
Run these commands in a empty folder and it should make a zip file that will work with the current version Blender.
Make sure to have `curl` and `cmake` installed before running this commands.

**Comment by AliaKhin** [comment]
> Guess I'll write the commands I used to make this work.

Thank you! It is working now after these commands. (Except I zipped it with another command but it is insignificant)
![image](https://user-images.githubusercontent.com/105072755/183861739-684cb043-4475-4481-916c-f91428ae6318.png)


Here is renamed archive that is working if someone will need to look inside it
[SourceIO linux working.zip](https://github.com/REDxEYE/SourceIO/files/9298598/SourceIO.linux.working.zip)

**Comment by AliaKhin** [comment]
.mdl importing works seemengly flawlessly but Source texture (.vtf) import outputs this error:
![image](https://user-images.githubusercontent.com/105072755/183868885-4614cdd7-5706-46a0-8056-7c8789ed5aac.png)
Tried it with what I had and downloaded new sfm mode with textures for experiment (https://steamcommunity.com/sharedfiles/filedetails/?id=2842601818&searchtext=). The error is same. (I'm sorry if this text is hard to read because of bad grammar and I hope it will be useful)

**Comment by REDxEYE** [comment]
I'm working on a vtflib replacement to get rid of libtxc_dxtn dependency

**Comment by TuxoYKT** [comment]
Building [libtxc_dxtn](https://aur.archlinux.org/packages/libtxc_dxtn) from AUR may solve your issue.

**Comment by AliaKhin** [comment]
> Building [libtxc_dxtn](https://aur.archlinux.org/packages/libtxc_dxtn) from AUR may solve your issue.

It actually is. Now trick will to memorize it because this requirement is nowhere to see in github readme page. Thank you again!

**Comment by Architector4** [comment]
Just ran into the same issue on Arch Linux by downloading the latest stable release, and compiling that nondescriptive "pylib.so" and replacing it fixes it. Just to reiterate for others running into the same issue later:

1. `git clone --recurse-submodules -j8 'https://github.com/REDxEYE/pylib.git'`
2. `cd pylib`
3. `cmake .`
4. `make`
5. `cp pylib.so ~/.config/blender/3.4/scripts/addons/SourceIO/library/utils/pylib_loader/unix/pylib.so` (adjust path to fit your blender version)

Considering that this seems like a common issue on Linux, it might be worth it to include this process or at least some hints in the readme; or, if somehow possible, make the library generic over any version of Python?

**Comment by REDxEYE** [comment]
@Architector4 Try switching to `refactor` branch of SourceIO  (`pure-native` branch for pylib)

**Comment by REDxEYE** [comment]
It's a version of pylib that does not depend on any python version

**Comment by Architector4** [comment]
Yup, refactor branch works out of the box.

Updated instruction for others in the future lmao

1. `git clone --recurse-submodules 'https://github.com/REDxEYE/SourceIO.git'`
2. `cd SourceIO`
3. `git checkout refactor`
4. `rm -rf .git` (will save space on importing the addon lol)
5. Create a zip file containing the entire `SourceIO` directory with all the stuff in that directory in that zip file
6. Import that
