### ISSUE TITLE
Some textures are not getting imported and stay pink

### ISSUE THREAD

**Issue by EntityinArray** [REDxEYE/SourceIO#159]
Hi! Thank you for your work on this amazing addon!

I faced an issue, where some textures are not getting imported and stay purple.
![image](https://user-images.githubusercontent.com/18554021/189733436-e79e45bd-7b66-4cc8-a431-99e9661c12a8.png)

Here I tried to import gm_flatgrass from Garry's Mod.
The only two textures that failed to import are ```maps/gm_flatgrass/concrete/concretefloor028c``` and ```maps/gm_flatgrass/concrete/concretefloor028a```
I tried looking through the log, but couldn't find any error messages. Addon says that material is found and then enters a weird loop, trying to import it over and over again:
```
[INFO]--[gm_flatgrass.bsp:load_materials]: Loading maps/gm_flatgrass/concrete/concretefloor028c_0_96_-12032 material
[INFO]--[ContentManager:find_file]: Requesting materials/maps/gm_flatgrass/concrete/concretefloor028c_0_96_-12032.vmt file
[DEBUG]--[ContentManager:find_file]: Found in gm_flatgrass!
[INFO]--[ContentManager:find_file]: Requesting materials/CONCRETE/CONCRETEFLOOR028C.vmt file
[DEBUG]--[ContentManager:find_file]: Found in hl2_misc_dir!
[INFO]--[Shaders::lightmappedgeneric:create_nodes]: Creating material 'maps/gm_flatgrass/concrete/concretefloor028c'
[INFO]--[ContentManager:find_file]: Requesting materials/concrete\concretefloor028c.vtf file
[INFO]--[ContentManager:find_file]: Requesting materials/concrete\concretefloor028c_normal.vtf file
[INFO]--[gm_flatgrass.bsp:load_materials]: Loading maps/gm_flatgrass/concrete/concretefloor028c_0_-1439_-12736 material
[INFO]--[ContentManager:find_file]: Requesting materials/maps/gm_flatgrass/concrete/concretefloor028c_0_-1439_-12736.vmt file
[DEBUG]--[ContentManager:find_file]: Found in gm_flatgrass!
[INFO]--[ContentManager:find_file]: Requesting materials/CONCRETE/CONCRETEFLOOR028C.vmt file
[DEBUG]--[ContentManager:find_file]: Found in garrysmod_fallbacks_dir!
[INFO]--[Shaders::lightmappedgeneric:create_nodes]: Creating material 'maps/gm_flatgrass/concrete/concretefloor028c'
[INFO]--[gm_flatgrass.bsp:load_materials]: Loading maps/gm_flatgrass/concrete/concretefloor028c_0_1312_-12736 material
[INFO]--[ContentManager:find_file]: Requesting materials/maps/gm_flatgrass/concrete/concretefloor028c_0_1312_-12736.vmt file
[DEBUG]--[ContentManager:find_file]: Found in gm_flatgrass!
[INFO]--[ContentManager:find_file]: Requesting materials/CONCRETE/CONCRETEFLOOR028C.vmt file
[DEBUG]--[ContentManager:find_file]: Found in garrysmod_fallbacks_dir!
[INFO]--[Shaders::lightmappedgeneric:create_nodes]: Creating material 'maps/gm_flatgrass/concrete/concretefloor028c'
```

Full log is available here: 
[blender.log](https://github.com/REDxEYE/SourceIO/files/9551058/blender.log)

Blend 3.3 LTS file with failed import here:
[gm_flatgrass.zip](https://github.com/REDxEYE/SourceIO/files/9551074/gm_flatgrass.zip)

Steam and Garry's Mod are both installed into ~/.steam, the default directory

OS: Fedora Linux 36
Blender 3.3 LTS, also occurs in 2.93 LTS
Source IO 4.0.3

Feel free to ask if any additional information is needed, I will be glad to help.
Thanks!

**Comment by REDxEYE** [comment]
Tested on fresh gmod install, everything loaded correctly

**Comment by REDxEYE** [comment]
It just failed to find some texture for unknown for me reason
![image](https://user-images.githubusercontent.com/17544576/193405234-2cfb3850-e0fb-445e-83b7-b9f8e44248bf.png)
