### ISSUE TITLE
Import mdl > Normalize Bones: Root/Pelvis bone locked translation

### ISSUE THREAD

**Issue by Irmitya** [REDxEYE/SourceIO#16]
When you import a model using Normalize, there is a potential for a weird thing in Blender. 

What happens is no matter what you do, a bone's location can't change (moving/constraints/drivers/etc), and the solution isn't obvious

In order to fix it, you have to go into edit mode, then Alt+P > Clear Parent, to disable the Connected property of the bone.

When a bone has the use_connected property, it locks it to it's parent. Thing is, if the bone doesn't have a parent, it locks to nothing. 
I would think Blender would notice it doesn't have a parent and move on but that's not the case.

This is the model I found this on:
https://sfmlab.com/item/3113/

**Comment by REDxEYE** [comment]
Should be fixed in latest commit on dmx-import branch
