### ISSUE TITLE
[Game] Titanfall 2 mdl and vpk's dont open.

### ISSUE THREAD

**Issue by KursedKrabbo** [REDxEYE/SourceIO#160]
seen this and noticed how streamlined it makes things and tried to do it with some titanfall 2 and titanfall 1 models im trying to extract, however im getting "mdl v52 unsupported"
hopefully this can be fixed, if not thats ok, but id really appriciate it :)

**Comment by KursedKrabbo** [comment]
[Titanfall 1 Online MDL files.zip](https://github.com/REDxEYE/SourceIO/files/9571686/Titanfall.1.Online.MDL.files.zip)
these are afew examples.

**Comment by KursedKrabbo** [comment]
also, to be more specific, i tried the "Preacher" one and the "IMC br" one

**Comment by REDxEYE** [comment]
You forgot to upload vvd and vtx files

**Comment by IJARika** [comment]
Titanfall 2 mdl (v53) has vvd/vtx inside the actual mdl file. I can provide structs for whatever is needed if you wish to add support, as well as examples.

**Comment by REDxEYE** [comment]
I have support for titanfall2 models

**Comment by REDxEYE** [comment]
MDL uploaded are to small to contain vtx/vvd

**Comment by REDxEYE** [comment]
Yep, just checked. This files do not contain vvd/vtx

**Comment by IJARika** [comment]
"TFO mdls are just v52 like normal Titanfall 1, so they should be working fine."

See the zip being named Titanfall 1 Online. As you know V52 just has external vtx/vvd obviously as you have added support. As for Titanfall 2 I see no mention of v53 in your code but maybe I'm blind? It also doesn't work for me (tool version 4.0.2).

Titanfall 1, 2, and Apex Legends VPK are also different which would be the other part of this issue.

I've attached a zip of both the Titanfall Online models Krabbo sent with vtx/vvd/phy and a zip that actually has Titanfall 2 models.


[tfo full.zip](https://github.com/REDxEYE/SourceIO/files/9911899/tfo.full.zip)
[v53.zip](https://github.com/REDxEYE/SourceIO/files/9911908/v53.zip)

**Comment by REDxEYE** [comment]
Titanfall2 vpk are supported, they are using variation of LZ compression called LZHAM
Apex uses the same format as Titanfall2

**Comment by REDxEYE** [comment]
![image](https://user-images.githubusercontent.com/17544576/199279936-8d4f1cea-b12f-4799-adbb-463c2f1cd084.png)
TFO model loaded perfectly
