### ISSUE TITLE
Props on .bsp map import as empty objects

### ISSUE THREAD

**Issue by Escapistmatt** [REDxEYE/SourceIO#161]
Hello, I tried importing this .bsp map into blender: https://sfmlab.com/project/28113/
I opened it in a map viewer and the props are all there.
The environment and lights all get imported correctly, but the props all become empties:

![Bad](https://user-images.githubusercontent.com/114092839/191548905-83059ee7-4792-421e-a017-b71a50437ad7.PNG)

Other source models and maps work, just this one seems to be a problem.

I have Blender 3.2.1 and the most recent version of SourceIO

**Comment by REDxEYE** [comment]
Please take a look at https://github.com/REDxEYE/SourceIO/blob/master/wiki/BSP_IMPORT.md

**Comment by Escapistmatt** [comment]
Oh sorry, my bad. I tried looking for solutions beforehand but guess I overlooked that...
