### ISSUE TITLE
Feature request: uniform material name format and combine based on vmt files

### ISSUE THREAD

**Issue by RenWuJun** [REDxEYE/SourceIO#162]
The uniform material name format can replace the old format or as an option when importing the map or props

Material names in the old format:
CONCRETE/CONCRETE_BTS_FLOOR002B_TOP
walkway_support_a_railing_underground
railing_256b_railing_underground
maps/sp_a3_transition01/metal/factory_metal_floor001b

Will be these in the new format:
concrete_bts_floor002b_top
railing_underground
factory_metal_floor001b

**Comment by REDxEYE** [comment]
material name contains full path due to name collisions. 
Normalizing to the lower case can be done.

**Comment by RenWuJun** [comment]
about the name collisions, is it possible to add a process at the end of the import that tells materials:
walkway_support_a_railing_underground
railing_256b_railing_underground
are the same material and create new material: railing_underground to replace
walkway_support_a_railing_underground
railing_256b_railing_underground

**Comment by REDxEYE** [comment]
I don't get what you want

**Comment by RenWuJun** [comment]
If you are asking what feature I want, then I just describe what feature I want
If you are asking what this feature benefits me, I need a uniform material name to make presets that can apply to new maps imported with one click, also I don't want to apply tweaks to dozens of other materials based on the same vmt file but got different head names manually after I tweak one

**Comment by REDxEYE** [comment]
Materials now have "full_path" property attached to them. You can access it like 
```python
bpy.data.materials["MATERIAL_NAME"]["full_path"]
```
Or just 
```python
for mat in bpy.data.materials:
  if mat["full_path"]=="TARGET_PATH":
    do_stuff()
```
