### ISSUE TITLE
Add VPK progress tracker to to-do list

### ISSUE THREAD

**Issue by ChandelureF-5** [REDxEYE/SourceIO#164]
It would really help to have it there so that we know how far in development it is.

**Comment by REDxEYE** [comment]
I don't have plans to develop SourceIO for now. I switched to SourceIO2

**Comment by ChandelureF-5** [comment]
There's a sequel?

**Comment by ChandelureF-5** [comment]
Well, stripe me up with skunk pattern and call me a badger, this isn't really relevant right now.
Once you merge the two into some hyper-addon, let me know, ok?

**Comment by REDxEYE** [comment]
SourceIO2 is just full rewrite of SourceIO.
I got tired of fixing old code and decided to rewrite it with better structuring and better code style
