### ISSUE TITLE
Some maps does not work?

### ISSUE THREAD

**Issue by cblpop** [REDxEYE/SourceIO#171]
Hello, i heff a Q.
Is there some maps that totally refuse to import?
For example https://steamcommunity.com/sharedfiles/filedetails/?id=1710466295
Map fine working in sfm, yet when i try to blender import it, it just load only map carcass without textures and literally most of entities does not spawn when you click load entity...
![SN](https://user-images.githubusercontent.com/50052826/198153925-f384b149-24fc-499a-bcc2-0a70f1938645.jpg)

**Comment by cblpop** [comment]
Ok after attempt to turn on brains and try to find why some map import work well and some are not i realised that creating in EVERY MOD folder "gameinfo.txt" file and write there mod folder name will solve the problem of map importing. But heres another problem is that some entities (im my case some trees) using materials that uses "Patch" shader. So they loading without textures.
Soo... is there any way to force sourceio to just load it as vertexlitgeneric???

**Comment by REDxEYE** [comment]
Patch shader is supported. The only way it can fail is when target material wasn't found

**Comment by cblpop** [comment]
Oh im dumb, i noticed that i can download sourceio zip from main page, not on "release" tab and it worked well with this tree, while 4.0.3 version from release tab were strongly refusing to load material while it were write in scripting tab that it found material

**Comment by cblpop** [comment]
ty for great plugin btw :)
