### ISSUE TITLE
Documentation for how to import skyboxes?

### ISSUE THREAD

**Issue by ferry-creator** [REDxEYE/SourceIO#174]
Hello. I'm attempting to import skyboxes by importing for example: `cstrike>materials>skybox>assultbk.vmt`
I know this is only the back of the skybox, so i also tried importing all 6 materials related to assult. But something tells me these are the wrong files entirely, what exactly material can i import to test out skyboxes? :D

Best regards, and thanks so much!

**Comment by ferry-creator** [comment]
Oh i just realized i should have asked this question on discord.... Sorry!

**Comment by ferry-creator** [comment]
Well i reopened since no one on Discord seems to know how to use it either :D But it seems like their is a posibility to import just a skybox directly?

**Comment by REDxEYE** [comment]
Just import one of the skybox(one of 6) materials. SourceIO will pull other faces automatically

**Comment by ferry-creator** [comment]
Yea i figured it out, then to apply the skybox you go to world settings and set the color texture to environment texture, and then you can select a texture after import. It stitches them automatically by just importing one of the materials, it's aweomse man thanks @REDxEYE
