### ISSUE TITLE
Eye movement sliders doesn't import for models if it's in the group of "Face"

### ISSUE THREAD

**Issue by iliekbaconssomuck** [REDxEYE/SourceIO#176]
SFM: ![image](https://user-images.githubusercontent.com/122763027/212589860-4b188bec-1b9b-4a9e-bf56-65da5377dad6.png)

Blender: ![image](https://user-images.githubusercontent.com/122763027/212589195-0c383172-173a-46a3-a9a5-f225dace8933.png)

It's specified in the group of faces as because if it's in the group of "Unknown" it does work. If I'm just bein a idiot and it's actually there (somewhere) lemme know :)

**Comment by REDxEYE** [comment]
eyes_updown/leftright are not real flexes, they cannot be imported nor there any easy way to replicate something similar automatically

**Comment by iliekbaconssomuck** [comment]
Ahh make sense, I can always use UV Editing to rotate them.
