### ISSUE TITLE
Maps have a border around it not allowing the preset "Sun" to work, deleting "world geometry" on some maps causes everything except props to be deleted (unless if the entire map are individual parts)

### ISSUE THREAD

**Issue by iliekbaconssomuck** [REDxEYE/SourceIO#178]
![image](https://user-images.githubusercontent.com/122763027/215360487-71548015-f7a5-49d2-aa4c-7c9c2d45ff85.png)
![image](https://user-images.githubusercontent.com/122763027/215360491-48abfefb-9d12-4574-b223-22f69be49f5f.png)

**Comment by REDxEYE** [comment]
Borders are sky polygons, just delete all polygons with sky material assigned. 
Sky polygons are part of the map.
