### ISSUE TITLE
Error Importing Addon

### ISSUE THREAD

**Issue by iHeartGamesYT** [REDxEYE/SourceIO#184]
When I try to install the addon I keep getting an error, like a Traceback error. How do I fix it?

**Comment by iHeartGamesYT** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/126117323/220765150-eb0088a4-7ad2-4b1f-b9b9-e8a93b50e31d.png)

**Comment by REDxEYE** [comment]
Use Blender 3.1 or newer
