### ISSUE TITLE
[2 Issues] Loading dynamic props/static are way too big when done loaded. V5.0.1 has the props, V5.0.2 doesn't.

### ISSUE THREAD

**Issue by WhenYouMe** [REDxEYE/SourceIO#186]
[ISSUE 1]

![image](https://user-images.githubusercontent.com/122762873/224483613-2853e6a1-a86d-4f92-9cd5-e315caea8584.png)
^Before Loading^ (Dynamic Props, ex 1) [V5.0.1]
![image](https://user-images.githubusercontent.com/122762873/224483621-0477d1f1-3760-4da2-b313-b47be8132f99.png)
^After Loading^ (Dynamic Props, ex 1) [V5.0.1]

![image](https://user-images.githubusercontent.com/122762873/224485456-fc7ce1f9-b374-4c6a-aa2d-9bb5ed0bd113.png)
^Before Loading^ (Static Props, ex 2) [V5.0.1]
![image](https://user-images.githubusercontent.com/122762873/224485499-bbcc868c-1291-4343-a979-cfac17b0026b.png)
^After Loading^ (Static Props, ex 2) [V5.0.1]

[ISSUE 2]

![image](https://user-images.githubusercontent.com/122762873/224485924-2ea158db-23b5-4273-895a-7090ac9acd8f.png)
^ERROR WHEN IMPORTING^ [V5.0.2]
![image](https://user-images.githubusercontent.com/122762873/224485943-938330e3-6285-44e4-8cb6-b68f5e8c4a1a.png)
^AFTER IMPORTING^ [V5.0.2]

**Comment by REDxEYE** [comment]
Big props are so-called "master collection", just **hide** it(not disable it) 

Also, please provide into about game and map you're trying to load

**Comment by WhenYouMe** [comment]
Hi, the first issue was fixed by the solution above. Issue 2 has also been fixed by a restart, the map used as the example is "forest_dim" [https://steamcommunity.com/sharedfiles/filedetails/?id=252027525](url), more specifically "forest_dim_daytime", restarting Blender and importing the .bsp now works without errors.
![image](https://user-images.githubusercontent.com/122762873/224487627-5b49be3e-9ccc-4502-ab59-5559bdf43a53.png)
