### ISSUE TITLE
Error on the model

### ISSUE THREAD

**Issue by furry72** [REDxEYE/SourceIO#189]
When import the model, the model is broken now
like this
![error de pomni](https://user-images.githubusercontent.com/114935255/226722013-f5e4a861-e84d-4c6f-9894-3168bc830356.png)

**Comment by furry72** [comment]
especially the Pomni model

**Comment by REDxEYE** [comment]
Try to reset bone transforms

**Comment by furry72** [comment]
but is the new release

**Comment by furry72** [comment]
REDxEYE, reset bone transform is useless, we can fix the model fixing thias addon

**Comment by furry72** [comment]
When import the Pomni model from Duz1771, and when import the position is incorrect... Fix this atrocity.... NOOOOW
