### ISSUE TITLE
"Load Entity" sets the props scale and location different to the parent object

### ISSUE THREAD

**Issue by Wildkale** [REDxEYE/SourceIO#190]
Whenever I use the **Load Entity** button on the SourceIO tab while selecting a handful of prop_statics or prop_dynamics, it brings the model into the blender scene but it places the model's scaling and xyz location differently than where the prop_statics or prop_dynamics currently sits, also unparenting the new mesh it brought it from the prop. 

**On top of this**, sometimes most of the prop_statics or prop_dynamics won't even load a model, and just leave me with a message saying it failed to find the model even though it's in the directory it's stating it's missing from.

I am currently using **Blender 3.2.2** with the **latest SourceIO** with no other extra plugins enabled or added.

**Comment by REDxEYE** [comment]
Please post the error log. And provide map file

**Comment by Wildkale** [comment]
This is the log I get when the model fails to import
**Failed to find mdl/vvd/vtx file for prop_dynamic_565714(models\hauptmann\star wars\architecture\vardos\vardos_city_bench.mdl) prop**

The main issue I've stated doesn't leave a log. I've attached a Google Drive link for its a big map
https://drive.google.com/file/d/1HX_AK7ZHhfrVjkkxCNSb2DM6JmM1xKmn/view?usp=sharing

**Comment by REDxEYE** [comment]
Logs are in console and embedded text blocks

**Comment by Wildkale** [comment]
bpy.ops.object.delete(use_global=False, confirm=False)
Deleted 3 object(s)
bpy.context.space_data.system_bookmarks_active = 3
Modules Installed (SourceIO) from 'C:\\Users\\kalei\\Downloads\\SourceIO(1).zip' into 'C:\\Users\\kalei\\AppData\\Roaming\\Blender Foundation\\Blender\\3.2\\scripts\\addons'
bpy.data.window_managers["WinMan"].addon_search = ""
bpy.data.window_managers["WinMan"].addon_search = ""
bpy.context.space_data.system_bookmarks_active = 3
bpy.data.window_managers["WinMan"].(null) = True
bpy.data.window_managers["WinMan"].(null) = True
bpy.data.window_managers["WinMan"].(null) = True
bpy.data.window_managers["WinMan"].(null) = True
bpy.data.window_managers["WinMan"].(null) = True
bpy.context.space_data.filter_text = "prop"
bpy.ops.outliner.item_activate(deselect_all=True)
bpy.ops.outliner.item_activate(extend_range=True, deselect_all=True)
Failed to find mdl/vvd/vtx file for prop_dynamic_148209(models\hauptmann\star wars\architecture\death_star\imperial_catwalk_stairs02.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_148254(models\hauptmann\star wars\architecture\death_star\imperial_catwalk_pillar_support01.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_54897(models\hauptmann\star wars\props\imperial\imperial_lamp.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_54968(models\hauptmann\star wars\props\imperial\imperial_lamp.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_54976(models\hauptmann\star wars\props\imperial\imperial_lamp.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_54980(models\hauptmann\star wars\props\imperial\imperial_lamp.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_84152(models\hauptmann\star wars\architecture\vardos\vardos_propaganda_poster03.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_84199(models\hauptmann\star wars\architecture\vardos\vardos_propaganda_poster03.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_18104(models\hauptmann\star wars\architecture\death_star\ds_platform_stairs02.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_18134(models\hauptmann\star wars\architecture\death_star\ds_platform_stairs02.mdl) prop
bpy.ops.outliner.item_activate(deselect_all=True)
bpy.ops.outliner.item_activate(extend_range=True, deselect_all=True)
bpy.ops.object.editmode_toggle()
bpy.ops.object.editmode_toggle()
bpy.ops.object.posemode_toggle()
bpy.ops.pose.armature_apply()
bpy.ops.object.posemode_toggle()
Failed to find mdl/vvd/vtx file for prop_dynamic_148254(models\hauptmann\star wars\architecture\death_star\imperial_catwalk_pillar_support01.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_148368(models\hauptmann\star wars\architecture\death_star\imperial_catwalk_pillar_support01.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_148372(models\hauptmann\star wars\architecture\death_star\imperial_catwalk_pillar_support01.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_148522(models\hauptmann\star wars\architecture\death_star\imperial_catwalk_stairs02.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_149048(models\hauptmann\star wars\architecture\death_star\imperial_catwalk_stairs02.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_149052(models\hauptmann\star wars\architecture\death_star\imperial_catwalk_pillar_support01.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_149057(models\hauptmann\star wars\architecture\death_star\imperial_catwalk_pillar_support01.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_149061(models\hauptmann\star wars\architecture\death_star\imperial_catwalk_pillar_support01.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_149065(models\hauptmann\star wars\architecture\death_star\imperial_catwalk_stairs02.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_149512(models\hauptmann\star wars\architecture\death_star\imperial_catwalk_stairs02.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_149516(models\hauptmann\star wars\architecture\death_star\imperial_catwalk_pillar_support01.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_149521(models\hauptmann\star wars\architecture\death_star\imperial_catwalk_pillar_support01.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_149525(models\hauptmann\star wars\architecture\death_star\imperial_catwalk_pillar_support01.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_149529(models\hauptmann\star wars\architecture\death_star\imperial_catwalk_stairs02.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_155630(models\starwars\syphadias\props\sw_tor\bioware_ea\props\sith\sith_tomb_statue_01.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_155634(models\starwars\syphadias\props\sw_tor\bioware_ea\props\sith\sith_tomb_statue_01.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_155638(models\starwars\syphadias\props\sw_tor\bioware_ea\props\sith\sith_tomb_statue_01.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_155642(models\starwars\syphadias\props\sw_tor\bioware_ea\props\sith\sith_tomb_statue_01.mdl) prop
bpy.context.space_data.context = 'MODIFIER'
bpy.ops.object.modifier_remove(modifier="Armature")
bpy.context.space_data.context = 'OBJECT'
bpy.context.space_data.context = 'COLLECTION'
bpy.data.collections["Collection"].instance_offset[0] = 606.6
bpy.data.collections["Collection"].instance_offset[1] = 508
bpy.context.space_data.context = 'DATA'
bpy.context.space_data.context = 'CONSTRAINT'
bpy.context.space_data.context = 'PHYSICS'
bpy.context.space_data.context = 'PARTICLES'
bpy.context.space_data.context = 'MODIFIER'
bpy.context.space_data.context = 'OBJECT'
bpy.context.scene.tool_settings.use_snap = True
bpy.ops.outliner.item_activate(deselect_all=True)
bpy.ops.outliner.item_activate(extend_range=True, deselect_all=True)
Failed to find mdl/vvd/vtx file for prop_dynamic_149521(models\hauptmann\star wars\architecture\death_star\imperial_catwalk_pillar_support01.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_149525(models\hauptmann\star wars\architecture\death_star\imperial_catwalk_pillar_support01.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_149529(models\hauptmann\star wars\architecture\death_star\imperial_catwalk_stairs02.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_155630(models\starwars\syphadias\props\sw_tor\bioware_ea\props\sith\sith_tomb_statue_01.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_155634(models\starwars\syphadias\props\sw_tor\bioware_ea\props\sith\sith_tomb_statue_01.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_155638(models\starwars\syphadias\props\sw_tor\bioware_ea\props\sith\sith_tomb_statue_01.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_155642(models\starwars\syphadias\props\sw_tor\bioware_ea\props\sith\sith_tomb_statue_01.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_155646(models\starwars\syphadias\props\sw_tor\bioware_ea\props\sith\sith_tomb_statue_01.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_155650(models\starwars\syphadias\props\sw_tor\bioware_ea\props\sith\sith_tomb_statue_01.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_155654(models\starwars\syphadias\props\sw_tor\bioware_ea\props\sith\sith_tomb_statue_01.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_155748(models\starwars\syphadias\props\sw_tor\bioware_ea\props\sith\sith_tomb_statue_01.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_155752(models\starwars\syphadias\props\sw_tor\bioware_ea\props\sith\sith_tomb_statue_01.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_155756(models\starwars\syphadias\props\sw_tor\bioware_ea\props\sith\sith_tomb_statue_01.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_155760(models\starwars\syphadias\props\sw_tor\bioware_ea\props\sith\sith_tomb_statue_01.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_155974(models\starwars\syphadias\props\sw_tor\bioware_ea\props\sith\sith_tomb_statue_01.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_155981(models\starwars\syphadias\props\sw_tor\bioware_ea\props\sith\sith_tomb_statue_01.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_155985(models\starwars\syphadias\props\sw_tor\bioware_ea\props\sith\sith_tomb_statue_01.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_197445(models\hauptmann\star wars\architecture\vardos\vardos_lightpole01.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_197525(models\hauptmann\star wars\architecture\vardos\vardos_lightpole01.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_197539(models\hauptmann\star wars\architecture\vardos\vardos_lightpole01.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_213887(models\hauptmann\star wars\architecture\death_star\imperial_catwalk_stairs02.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_213891(models\hauptmann\star wars\architecture\death_star\imperial_catwalk_pillar_support01.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_213895(models\hauptmann\star wars\architecture\death_star\imperial_catwalk_pillar_support01.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_213899(models\hauptmann\star wars\architecture\death_star\imperial_catwalk_pillar_support01.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_213903(models\hauptmann\star wars\architecture\death_star\imperial_catwalk_stairs02.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_214370(models\hauptmann\star wars\architecture\death_star\imperial_catwalk_stairs02.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_214374(models\hauptmann\star wars\architecture\death_star\imperial_catwalk_pillar_support01.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_197431(models\hauptmann\star wars\architecture\vardos\vardos_lightpole01.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_197459(models\hauptmann\star wars\architecture\vardos\vardos_lightpole01.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_197473(models\hauptmann\star wars\architecture\vardos\vardos_lightpole01.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_197511(models\hauptmann\star wars\architecture\vardos\vardos_lightpole01.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_197842(models\hauptmann\star wars\architecture\vardos\vardos_tree.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_197850(models\hauptmann\star wars\architecture\vardos\vardos_statue_versio.mdl) prop
bpy.context.space_data.system_bookmarks_active = 3
bpy.context.space_data.params.filename = "mdl"
bpy.context.space_data.params.filter_search = "mdl"
bpy.context.space_data.params.filter_search = ".mdl"
bpy.context.space_data.system_bookmarks_active = 3
bpy.context.space_data.system_bookmarks_active = 2
bpy.context.space_data.system_bookmarks_active = 3
Python: Traceback (most recent call last):
  File "C:\Users\kalei\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\SourceIO\blender_bindings\operators\source1_operators.py", line 49, in execute
    model_container = import_model_from_full_path(mdl_path, self.scale, self.create_flex_drivers,
  File "C:\Users\kalei\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\SourceIO\blender_bindings\source1\mdl\model_loader.py", line 35, in import_model_from_full_path
    vtx_file = FileBuffer(find_vtx(mdl_path))
  File "C:\Users\kalei\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\SourceIO\library\utils\file_utils.py", line 310, in __init__
    io.FileIO.__init__(self, file, mode, closefd, opener)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Python: Traceback (most recent call last):
  File "C:\Users\kalei\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\SourceIO\blender_bindings\operators\source1_operators.py", line 49, in execute
    model_container = import_model_from_full_path(mdl_path, self.scale, self.create_flex_drivers,
  File "C:\Users\kalei\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\SourceIO\blender_bindings\source1\mdl\model_loader.py", line 35, in import_model_from_full_path
    vtx_file = FileBuffer(find_vtx(mdl_path))
  File "C:\Users\kalei\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\SourceIO\library\utils\file_utils.py", line 310, in __init__
    io.FileIO.__init__(self, file, mode, closefd, opener)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Python: Traceback (most recent call last):
  File "C:\Users\kalei\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\SourceIO\blender_bindings\operators\source1_operators.py", line 49, in execute
    model_container = import_model_from_full_path(mdl_path, self.scale, self.create_flex_drivers,
  File "C:\Users\kalei\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\SourceIO\blender_bindings\source1\mdl\model_loader.py", line 35, in import_model_from_full_path
    vtx_file = FileBuffer(find_vtx(mdl_path))
  File "C:\Users\kalei\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\SourceIO\library\utils\file_utils.py", line 310, in __init__
    io.FileIO.__init__(self, file, mode, closefd, opener)
TypeError: expected str, bytes or os.PathLike object, not NoneType
bpy.ops.outliner.item_activate(deselect_all=True)
Failed to find mdl/vvd/vtx file for prop_dynamic_230793(models\hauptmann\star wars\architecture\vardos\vardos_lightpole01.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_230793(models\hauptmann\star wars\architecture\vardos\vardos_lightpole01.mdl) prop
bpy.ops.outliner.item_activate(deselect_all=True)
Failed to find mdl/vvd/vtx file for prop_dynamic_239160(models\hauptmann\star wars\vehicles\imperial\imperial_stardestroyer.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_239160(models\hauptmann\star wars\vehicles\imperial\imperial_stardestroyer.mdl) prop
bpy.ops.outliner.item_activate(deselect_all=True)
bpy.ops.outliner.item_activate(deselect_all=True)
bpy.ops.outliner.item_activate(deselect_all=True)
bpy.ops.outliner.item_activate(deselect_all=True)
Failed to find mdl/vvd/vtx file for prop_dynamic_565714(models\hauptmann\star wars\architecture\vardos\vardos_city_bench.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_565714(models\hauptmann\star wars\architecture\vardos\vardos_city_bench.mdl) prop
Failed to find mdl/vvd/vtx file for prop_dynamic_565714(models\hauptmann\star wars\architecture\vardos\vardos_city_bench.mdl) prop
bpy.ops.action.select_box(xmin=1203, xmax=1222, ymin=-4, ymax=23, mode='SET', tweak=True)
bpy.context.area.ui_type = 'CONSOLE'

**Comment by REDxEYE** [comment]
Can you re-import the map and then without doing anything else copy logs?

**Comment by Wildkale** [comment]
bpy.ops.object.delete(use_global=False, confirm=False)
Deleted 3 object(s)
bpy.context.space_data.system_bookmarks_active = 3
bpy.data.window_managers["WinMan"].(null) = True
bpy.data.window_managers["WinMan"].(null) = False
bpy.data.window_managers["WinMan"].(null) = True
bpy.data.window_managers["WinMan"].(null) = True
bpy.data.window_managers["WinMan"].(null) = True
bpy.data.window_managers["WinMan"].(null) = True
bpy.data.window_managers["WinMan"].(null) = True

**Comment by REDxEYE** [comment]
Restart blender before doing that

**Comment by REDxEYE** [comment]
Have you import map before copying logs?

**Comment by REDxEYE** [comment]
Okay, forget about it. Can you upload other map resources? Props. textures and etc? I'll try to debug it myself

**Comment by Wildkale** [comment]
sure, give me a moment

**Comment by REDxEYE** [comment]
I've checked, some prop model are not present in archive you sent

**Comment by Wildkale** [comment]
![image](https://user-images.githubusercontent.com/83934497/227246092-384f60ed-b094-4dab-bf1d-7f855b46fe95.png)
It seems to me that all the files are there but it doesn't want to open duplicate objects, like there is many "fence" props but on "Load Entity" it only loads one of the props with the identical model and not the rest
![image](https://user-images.githubusercontent.com/83934497/227246224-b9928006-8d0b-4bce-a006-64eff8b86c83.png)
Also here is an example of what the props that do want to import, look like. Big and out of its correct place

**Comment by Wildkale** [comment]
I am attaching a Blender Project File with the map loaded and nothing else done, maybe this could help
https://drive.google.com/file/d/19WR5AkIh8ImiqEWb4m_1kSTnUIaRVytZ/view?usp=sharing

**Comment by REDxEYE** [comment]
I was able to import the map with only a few missing models(50-60 entities out of 4k)

**Comment by Wildkale** [comment]
could you send it over using Google Drive?

**Comment by Wildkale** [comment]
if not, please email it to me at tippeetop@gmail.com

**Comment by Wildkale** [comment]
also, how did you get the map to import with the models attached, or what did you do to solve the "Load Entity" issue

**Comment by REDxEYE** [comment]
@Wildkale https://we.tl/t-N0vwhyQ8Mt Link will expire in 7 days

**Comment by Wildkale** [comment]
Got it thank you! Was there something I did wrong on my part that was causing me my issues?

**Comment by Wildkale** [comment]
![image](https://user-images.githubusercontent.com/83934497/227606366-ab998920-8445-4458-9d11-47e09ae4c530.png)
Also how can I convert this into a mesh instead a object

**Comment by REDxEYE** [comment]
> Got it thank you! Was there something I did wrong on my part that was causing me my issues?
> 
> And I'm seeing a lot of stuff in the blender scene that I didn't see before, could you tell me how you extracted the map so perfectly?

Just downloaded add required addons, extracted them into one folder and imported the map

**Comment by REDxEYE** [comment]
> ![image](https://user-images.githubusercontent.com/83934497/227606366-ab998920-8445-4458-9d11-47e09ae4c530.png) Also how can I convert this into a mesh instead a object

https://blenderartists.org/t/convert-collection-instance-to-mesh/1178001

**Comment by Wildkale** [comment]
> > ![image](https://user-images.githubusercontent.com/83934497/227606366-ab998920-8445-4458-9d11-47e09ae4c530.png) Also how can I convert this into a mesh instead a object
> 
> https://blenderartists.org/t/convert-collection-instance-to-mesh/1178001

Thank you so much

**Comment by SlavicSniper** [comment]
> @Wildkale https://we.tl/t-N0vwhyQ8Mt Link will expire in 7 days

Question do you still have the FBX or file in general?
