### ISSUE TITLE
Can't open mfs2020 mdl file - python traceback error

### ISSUE THREAD

**Issue by bEgemot32015** [REDxEYE/SourceIO#193]
Error while opening mdl taken from mfs2020 aircraft. Fix if u can pls.
[SAAD_A35K_V2.zip](https://github.com/REDxEYE/SourceIO/files/11131349/SAAD_A35K_V2.zip)

**Comment by REDxEYE** [comment]
Please post full error log

**Comment by REDxEYE** [comment]
This is not Source engine model. It's microsoft flight simulator model, two different formats
