### ISSUE TITLE
when trying to import hl1 map i get a "ValueError. too many values to unpack (expected 2). 

### ISSUE THREAD

**Issue by githubuserhl1** [REDxEYE/SourceIO#194]
it only works if i port it from my pc folder but then it has no textures so idk what to do. also hard-life maps dont work. but im more worried about the value error
![valueerror](https://user-images.githubusercontent.com/130783738/232109574-b76d087b-181c-437d-bcc7-4ead604c4727.png)

**Comment by REDxEYE** [comment]
Please provide full error log

**Comment by githubuserhl1** [comment]
ok
![fullerrorlog](https://user-images.githubusercontent.com/130783738/232128125-39fcfead-0e9d-4f01-9bba-b8fa12b63b14.png)

**Comment by githubuserhl1** [comment]
this happens with my hard life directory and my half life one

**Comment by REDxEYE** [comment]
Try updating sourceio to master

**Comment by githubuserhl1** [comment]
how do i do that and does it cost money?

**Comment by REDxEYE** [comment]
https://github.com/REDxEYE/SourceIO/archive/refs/heads/master.zip

**Comment by githubuserhl1** [comment]
thx

**Comment by githubuserhl1** [comment]
still doesnt work
same error

**Comment by Droooga** [comment]
Any chance of looking in to this issue more? Same error happens to me on both latest master and the 5.0.3 release.

**Comment by Droooga** [comment]
It seems to happen on BSPs that are compiled with non-Valve map compiling tools. For example I tried the base games c1a0.bsp, loaded all fine, and then 2 test maps I compiled with VHLT, which caused the error on both files.

I've attached the 2 maps I tried in case you wanna take a look yourself

[https://cdn.discordapp.com/attachments/926120049922678874/1126153086646370374/testt1.bsp](url) [https://cdn.discordapp.com/attachments/926120049922678874/1126153086315012157/testt2.bsp](url)

**Comment by staticanimal** [comment]
having this exact same issue with almost completely identical error log output except with every and any goldsrc bsp i attempt to import.

i've done this exact thing before and have had zero issues so i'm seriously confused as to why it's behaving this way suddenly

tested in blender 3.6.2 using sourceio 5.2.0

**Comment by REDxEYE** [comment]
Should be okay now.
