### ISSUE TITLE
Weird Error

### ISSUE THREAD

**Issue by sarcat91** [REDxEYE/SourceIO#195]
The "Source Assets" Option isn't appearing in my Import, I downloaded the SourceIO Release for 2.93+, The version of Blender i use is 3.3, Any reason why this is occuring? And if it's because i downloaded the wrong release of SourceIO, Can you link me to a version that will work with my version of Blender?

**Comment by REDxEYE** [comment]
Why are you downloading this one release?
Use 5.0.3 or master

**Comment by sarcat91** [comment]
OK
