### ISSUE TITLE
Strange Install Issue

### ISSUE THREAD

**Issue by Mosvelt** [REDxEYE/SourceIO#196]
Been having this problem with both the master and 5.0.3 versions, any help?

![image](https://user-images.githubusercontent.com/106959068/232877946-dbb6a827-c277-4316-9e91-7cac2816b35c.png)

**Comment by REDxEYE** [comment]
Blender 3.1+. Update, please

**Comment by Mosvelt** [comment]
> Blender 3.1+. Update, please

Thank you
