### ISSUE TITLE
would it be possible to add .gma support, or at least make a separate blender tool that serves the same purpose?

### ISSUE THREAD

**Issue by ChandelureF-5** [REDxEYE/SourceIO#201]

**Comment by REDxEYE** [comment]
.gma archive mount automatically. GMA is not a model or a map, it's archive similar to VPK or ZIP

**Comment by ChandelureF-5** [comment]
I don't quite understand, sorry

**Comment by REDxEYE** [comment]
Okay, let's start from the other end. What do you expect from "Import GMA"?

**Comment by REDxEYE** [comment]
What do you mean by use in blender?

**Comment by ChandelureF-5** [comment]
I mean like translate whatever it holds into a usable format by Blender, things such as that.

**Comment by REDxEYE** [comment]
Well, gma is usually bunch of models, textures, materials, maps. Not sure if it's a good idea to load everything

**Comment by ChandelureF-5** [comment]
How about this instead of loading everything: We do a similar kind of thing to the APKs, only with more GMod elements.

**Comment by ChandelureF-5** [comment]
~.~
At this point, I'm running out of ways to interpret the idea
Maybe just make a simplified version of what you were going for on the VPK browser, since it's probably less tedious to code for.

**Comment by REDxEYE** [comment]
As i said, VPK browser is deprecated and wasn't finished. There was no usable functions except just file listing

**Comment by REDxEYE** [comment]
Blender lacks UI element and functionality to implement proper file browser

**Comment by ChandelureF-5** [comment]
Well, let's wait for the functionality to be made then.
Or we could create a prototype involving code for extraction of all Source archive types, which might take longer, but it will certainly allow for easier loading of individual models than browsing some files for exactly what you want.
Whichever is easiest.

**Comment by REDxEYE** [comment]
Crowbar already can do that. You may use it to just unpack it and import

**Comment by ChandelureF-5** [comment]
<.>
aight let's just wait for ui functionality to come to blender then
imma try out crowbar to see if it's actually good in the meantime
