### ISSUE TITLE
Error again

### ISSUE THREAD

**Issue by furry72** [REDxEYE/SourceIO#202]
I'm imported the model and look this
![error again](https://github.com/REDxEYE/SourceIO/assets/114935255/2d4190a5-b0ea-4241-ba3d-c846e0d8481d)

**Comment by REDxEYE** [comment]
Please upload model files

**Comment by furry72** [comment]
Is the Duz1771 Pomni Update specially the Playermodel

**Comment by REDxEYE** [comment]
Player models with proportion trick are not supported and never will. Import non-player model version
