### ISSUE TITLE
What does this mean?

### ISSUE THREAD

**Issue by TheStyleHedgehog** [REDxEYE/SourceIO#209]
I tried, time and time again, And my blender continuously gives me this error.
I don't understand what it means so I tried looking here for answers.
![Screenshot 2023-06-04 181146](https://github.com/REDxEYE/SourceIO/assets/83103920/2c03ed88-5f60-400e-81c7-e803a5f7b46c)

**Comment by JackDainzh** [comment]
Download the zip from the Release section.

**Comment by REDxEYE** [comment]
Downloading the master is okay. Error you're facing something new. Try manually cleaning C:\Program Files\Blender Foundation\BLender 3.5\3.5\scripts\addons from old sourceIO installations
