### ISSUE TITLE
just downloaded the newer version and this keeps happening 

### ISSUE THREAD

**Issue by Doggylord356** [REDxEYE/SourceIO#210]
![Screenshot 2023-06-12 183107](https://github.com/REDxEYE/SourceIO/assets/136360070/0d0f83cd-c3e1-4472-8e39-92d31550df43)
this pops up everytime i import a map from sfm now..

**Comment by REDxEYE** [comment]
Something is wrong with maps you're trying to import. They are either newer version that sourceIO support or sourceIO incorrectly picked a reader for map+lump version

**Comment by Doggylord356** [comment]
hmm i see. it was working earlier when i installed the new stuff and got rid of all the old files

**Comment by REDxEYE** [comment]
Mind uploading few of the maps for me to test?

**Comment by Doggylord356** [comment]
they are the built in maps from sfm like 2 fort and manor event

**Comment by Doggylord356** [comment]
found the problem. i had named the file wrong
