### ISSUE TITLE
error when importing dmx/sfm session

### ISSUE THREAD

**Issue by MrMage750** [REDxEYE/SourceIO#213]
when importing a dmx/sfm session file, I get an error and only the camera properly imports

Read prefs: "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\config\userpref.blend"
Registered nodes
[INFO]--[ContentManager:register_content_provider]: Registered NonSourceContentProvider('bladesymphony') provider for bladesymphony
[INFO]--[ContentManager:register_content_provider]: Registered NonSourceContentProvider('dod') provider for dod
[INFO]--[ContentManager:register_content_provider]: Registered NonSourceContentProvider('tf_movies') provider for tf_movies
[INFO]--[ContentManager:register_content_provider]: Registered NonSourceContentProvider('tf') provider for tf
[INFO]--[ContentManager:register_content_provider]: Registered NonSourceContentProvider('hl2') provider for hl2
[INFO]--[ContentManager:register_content_provider]: Registered NonSourceContentProvider('left4dead2_movies') provider for left4dead2_movies
[INFO]--[ContentManager:register_content_provider]: Registered NonSourceContentProvider('dinodday') provider for dinodday
[INFO]--[ContentManager:register_content_provider]: Registered NonSourceContentProvider('portal2') provider for portal2
[INFO]--[ContentManager:register_content_provider]: Registered NonSourceContentProvider('portal2_dlc1') provider for portal2_dlc1
[INFO]--[ContentManager:register_content_provider]: Registered NonSourceContentProvider('portal2_dlc2') provider for portal2_dlc2
[INFO]--[ContentManager:register_content_provider]: Registered NonSourceContentProvider('stanleyparable') provider for stanleyparable
[INFO]--[ContentManager:register_content_provider]: Registered NonSourceContentProvider('usermod') provider for usermod
[INFO]--[ContentManager:register_content_provider]: Registered NonSourceContentProvider('platform') provider for platform
[INFO]--[ContentManager:register_content_provider]: Registered NonSourceContentProvider('workshop') provider for workshop
[INFO]--[ContentManager:find_path]: Requesting maps\stage_big.bsp file
[DEBUG]--[ContentManager:find_path]: Found in tf_movies!
Loading stage_big.bsp
[INFO]--[stage_big.bsp:__init__]: Loading map "C:\Program Files (x86)\Steam\steamapps\common\SourceFilmmaker\game\tf_movies\maps\stage_big.bsp"
[DEBUG]--[stage_big.bsp:__init__]: Adding map pack file to content manager
[INFO]--[ContentManager:find_file]: Requesting models\revamped_anthros\revamped_anthro_body_base_v4.mdl file
[DEBUG]--[ContentManager:find_file]: Found in usermod!
[INFO]--[ContentManager:find_file]: Requesting models\revamped_anthros\revamped_anthro_body_base_v4.vvd file
[DEBUG]--[ContentManager:find_file]: Found in usermod!
[INFO]--[ContentManager:find_file]: Requesting models\revamped_anthros\revamped_anthro_body_base_v4.dx90.vtx file
[DEBUG]--[ContentManager:find_file]: Found in usermod!
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\SourceIO-master\blender_bindings\operators\source1_operators.py", line 177, in execute
    load_session(directory / file.name, 1)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\SourceIO-master\blender_bindings\source1\dmx\load_sfm_session.py", line 122, in load_session
    load_animset(anim_set, shot, scale)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\SourceIO-master\blender_bindings\source1\dmx\load_sfm_session.py", line 81, in load_animset
    container = import_gamemodel(animset.game_model.model_name, scale)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\SourceIO-master\blender_bindings\source1\dmx\load_sfm_session.py", line 29, in import_gamemodel
    model_container = import_model(mld_file, vvd_file, vtx_file, None, scale, False, True)
TypeError: import_model() takes from 1 to 5 positional arguments but 7 were given

I'm well aware dmx files are a WIP with SourceIO, but this is something to note since it's currently being worked on

**Comment by REDxEYE** [comment]
Hello, DMX import feature will be cut in next release, as i dont have time nor will to work on that. There is to many variables there on how to interpret same data in different conditions
