### ISSUE TITLE
MDL format not working

### ISSUE THREAD

**Issue by Maselia464** [REDxEYE/SourceIO#217]
Hi

MDL format isn't getting imported into Blender.

Here's the error int eh file attach
![Screenshot_3](https://github.com/REDxEYE/SourceIO/assets/79214642/d9c42a0c-a855-4869-be1c-757f9d2cfd32)

**Comment by REDxEYE** [comment]
Disable physics import. Missing ,phy file for the model you are trying to import. 
This file may not exist in 2 cases:
- Model was compiled without physics mesh
- You forgot to unpack it from archive (gma/zip/vpk or any other archive type)

**Comment by REDxEYE** [comment]
Physics import is optional. So just disable physics import.

**Comment by Maselia464** [comment]
Problem was from the missing import like you stated.

thank you
