### ISSUE TITLE
SourceIO v3.5.4 - Not Installing Correctly

### ISSUE THREAD

**Issue by 0Curtain0** [REDxEYE/SourceIO#22]
**Blender v2.80 Official Release**
**Pop!_OS 64bit** (based on Ubuntu)
**SourceIO v3.5.4** (28c64ac - Oct 18 2019)

When attempting to install this release, It said: 
`Modules Installed () from '/home/user/Downloads/Blender/addons/SourceIO/2-8x/20191018/SourceIO.zip' into '/home/user/.config/blender/2.80/scripts/addons'`

However, the add-on does not appear in the **Blender Preferences** - **Add-ons** menu. 
I did not see any error messages in the **Scripting** section.

I'm not a programmer, but I also took a look at the __init__.py in a text editor and noticed the version is still showing **3.5.1**.

**EDIT**
Also, the **bl_info** appears to be inside the **if bpy_available**, not sure if it's supposed to be like that.

According to Blender wiki:
> You must include a python dictionary named "bl_info" at the top of your addon .py file or __init__.py if your Addon is a Python module.

```
bl_info = {
    "name": "My Script",
    "description": "Single line explaining what this script exactly does.",
    "author": "John Doe, Jane Doe",
    "version": (1, 0),
    "blender": (2, 65, 0),
    "location": "View3D > Add > Mesh",
    "warning": "", # used for warning icon and text in addons panel
    "wiki_url": "http://wiki.blender.org/index.php/Extensions:2.6/Py/"
                "Scripts/My_Script",
    "tracker_url": "https://developer.blender.org/maniphest/task/edit/form/2/",
    "support": "COMMUNITY",
    "category": "Add Mesh"
}
```

**Comment by REDxEYE** [comment]
fixed in latest commit

**Comment by 0Curtain0** [comment]
**Blender v2.80 Official Release**
**Pop!_OS 64bit** (based on Ubuntu)
**SourceIO** v**3.5.4.1** (03b090e - Oct 20 2019)

The new hot fix has the same problem as v**3.5.4**.

Also, is there supposed to be an indentation for bl_info?
https://i.imgur.com/p9vXpJF.png
I didn't see that indentation in v**3.5.1** (Jul 30 2019) release.

**Comment by REDxEYE** [comment]
I think i got it, will be fixed in next commit

**Comment by REDxEYE** [comment]
Try now

**Comment by REDxEYE** [comment]
Fixed!
