### ISSUE TITLE
Error while importing Valve Source MDL files into blender.

### ISSUE THREAD

**Issue by ItsKingSilas** [REDxEYE/SourceIO#220]
While trying to import Half Life 2 Episode 2 tree models into Blender, I received a big error when I clicked import. I believe it was a python error. I'll provide a screenshot of the error.

Can anyone help?

![Screenshot_10](https://github.com/REDxEYE/SourceIO/assets/140994597/1098531f-06cc-4f8a-b94b-7e6ea5493f9d)

**Comment by REDxEYE** [comment]
Are you on latest version of SourceIO

**Comment by ethanpriore** [comment]
I'm getting the same error, and yes, I have the latest version of SourceIO.  I tried mdl files that weren't from original source games, like an sprop mdl from gmod, but that gave a similar error.

**Comment by ItsKingSilas** [comment]
> Are you on latest version of SourceIO

Yes, I am on the current version. I've also tried the Source-IO Master.

**Comment by REDxEYE** [comment]
Can you upload models that fail to import? Don't forget to include .vtx and .vvd files, as they are part of a model and without them i cannot test the model

**Comment by ItsKingSilas** [comment]
Github doesn't support that file type, is there any other way to upload?

**Comment by REDxEYE** [comment]
zip it up and drop it into the message window
![image](https://github.com/REDxEYE/SourceIO/assets/17544576/992236a6-1f25-4bd7-9e3b-38666130bea2)

**Comment by ItsKingSilas** [comment]
[Valve Model.zip](https://github.com/REDxEYE/SourceIO/files/12222930/Valve.Model.zip)
It's a tree MDL model

**Comment by REDxEYE** [comment]
You forgot to include .vtx and .vvd

**Comment by ItsKingSilas** [comment]
> You forgot to include .vtx and .vvd

Sorry, I originally read that as "Don't" include them. 

When exporting the MDL files with crowbar, they didn't come with the VTX or VVD

**Comment by ItsKingSilas** [comment]
> You forgot to include .vtx and .vvd
[ep2_pak_dir.zip](https://github.com/REDxEYE/SourceIO/files/12224107/ep2_pak_dir.zip)

Original comment above is obsolete, I found the VPK i took them from but no VVD file.

**Comment by REDxEYE** [comment]
![image](https://github.com/REDxEYE/SourceIO/assets/17544576/1709ed0d-91a7-4bc9-8132-1d23da8dccd6)
All files are there. You need to export all 3 (mdl, vvd, and any of vtx(preferably dx90))
