### ISSUE TITLE
Report Error: "source Io Not installed"

### ISSUE THREAD

**Issue by toby1603** [REDxEYE/SourceIO#222]
When i select a mdl strategy and selected the game definition it didn't work it said, "source Io Not installed" Pls help me fix it
![Screenshot 2023-08-05 072901](https://github.com/REDxEYE/SourceIO/assets/141464072/b75e286b-1dc3-475a-8797-357439625389)

**Comment by REDxEYE** [comment]
Have you tried installing SourceIO addon?

**Comment by toby1603** [comment]
Yeah, i did and installed it and the option source engine model was enabled.

**Comment by toby1603** [comment]
![Screenshot 2023-08-05 073333](https://github.com/REDxEYE/SourceIO/assets/141464072/1949045e-1930-467b-89c5-a67ee303801e)

**Comment by REDxEYE** [comment]
Probably io_import_vmf is not compatible with SourceIO. Create an issue in io_import_vmf repo about it

**Comment by toby1603** [comment]
I see well then if it still doesn't works I will be going back to this issue.
