### ISSUE TITLE
no tutorial in description

### ISSUE THREAD

**Issue by pinkjimrussiagirl** [REDxEYE/SourceIO#227]
i have downloaded and extracted the addon on my computer, but there is no tutorial in the description showing me how to install it to blender, and i don't use discord so i can't install it if the instructions are only on the discord server so please add the instructions in the description so people can see how to install it without having to join the discord server

edit: i noticed that i didn't need to extract the file to be able to install it to blender

**Comment by REDxEYE** [comment]
SourceIO installs just like any other addon. I don't think that it need instructions on blender built-in functionality on the addon page.

**Comment by pinkjimrussiagirl** [comment]
ok, also i already figured it out since i never installed a blender addon before which is why i didn’t know about how to install them

bee

[signatureImage]
________________________________
