### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by BoredInGames** [REDxEYE/SourceIO#228]
Ngl Im a newbie at Blender stuff and no matter all the research I did about the problem I can't seem to find anything about it, any clues on what it could be ?

![BlendahProbs](https://github.com/REDxEYE/SourceIO/assets/143852455/27de1697-eb40-4b67-87da-77e1e87b9d94)

**Comment by REDxEYE** [comment]
Its a weird blender but. Uninstall addon. Delete all sourceio.zip files from your downloads folder and downoad it again
