### ISSUE TITLE
3.5.4 is not working

### ISSUE THREAD

**Issue by CelsoBlackfyre** [REDxEYE/SourceIO#23]
The version 3.5.4 is not installing correctly, it doesn't show up on blender.....

**Comment by REDxEYE** [comment]
Any errors in console? Are you on linux?

**Comment by CelsoBlackfyre** [comment]
> Any errors in console? Are you on linux?

Actually not, I use windows, it just closes and doesn't show nothing, it's like not accepting as an addon

**Comment by REDxEYE** [comment]
Start blender with "-con" parametr, and check console after blender fully loaded

**Comment by CelsoBlackfyre** [comment]
> Start blender with "-con" parametr, and check console after blender fully loaded

![Screenshot_175](https://user-images.githubusercontent.com/32004864/67150752-2ae04a80-f292-11e9-9ee7-87859a2711e7.png)

**Comment by REDxEYE** [comment]
Okay, gonna try to fix it right now

**Comment by REDxEYE** [comment]
Try instaling latest commit

**Comment by CelsoBlackfyre** [comment]
> Try instaling latest commit

hey man, can you link me the updated one ? I'm not familiar with this site and I get confused, I'm download the same one I think ...

**Comment by justausernamesfm** [comment]
> Try instaling latest commit

I had the same problem but the latest commit works now. 

> hey man, can you link me the updated one ? I'm not familiar with this site and I get confused, I'm download the same one I think ...

On the code page click "clone or download" and click download as zip, then install it normally.

**Comment by CelsoBlackfyre** [comment]
> > Try instaling latest commit
> 
> I had the same problem but the latest commit works now.
> 
> > hey man, can you link me the updated one ? I'm not familiar with this site and I get confused, I'm download the same one I think ...
> 
> On the code page click "clone or download" and click download as zip, then install it normally.

Lmao still not working for me, trying everything, clone and download and the new hotfix download...wtf is happening ?

**Comment by CelsoBlackfyre** [comment]
It works now, thank you man!
