### ISSUE TITLE
traceback errors

### ISSUE THREAD

**Issue by dexelbro** [REDxEYE/SourceIO#231]
Keep getting traceback errors when trying to import vmap_c files

**Comment by REDxEYE** [comment]
Please provide a screenshot or copy error text

**Comment by dexelbro** [comment]
![screenshot 220](https://github.com/REDxEYE/SourceIO/assets/103148104/2f5aaf29-643e-4e19-b1c1-e82164ca9294)

**Comment by REDxEYE** [comment]
This path does not look valid
Why de_inferno.vpk is doing in sourceIO folder? What is this folder?

Source2 maps must be imported from their original directory.

**Comment by dexelbro** [comment]
Ok, so I imported using source 2 packed map vpk option from the original directory. Now I have these static props nodes. What do I do next?
![screenshot 221](https://github.com/REDxEYE/SourceIO/assets/103148104/d18dfa43-5b08-49ab-a54b-7b9f4e351112)

**Comment by REDxEYE** [comment]
Select few of them and click load entity in SourceIO tool panel

**Comment by dexelbro** [comment]
Got it. What does this mean?
![screenshot 222](https://github.com/REDxEYE/SourceIO/assets/103148104/d3738e9a-a879-4b01-8dbf-743f228080a7)

**Comment by REDxEYE** [comment]
Unsupported data type. What model are you trying to import?

**Comment by dexelbro** [comment]
I'm trying to import a CS2 map

**Comment by REDxEYE** [comment]
Should be fixed now
