### ISSUE TITLE
Entities have texture in viewport, but nothing in shading tab

### ISSUE THREAD

**Issue by Arazrajabi** [REDxEYE/SourceIO#234]
I imported a bsp map. Then loaded static props/entities.

Every thing looks fine in viewport. But in shading tap, static props have no material or texture!!! Where as they look completely normal in viewport.
This makes problem whenever I try to export these static props in every format(fbx, obj, glb ). Exported file has no material or texture. World geometry has material and texture and everything is fine about that. But static props no.
It is a gmod map

**Comment by REDxEYE** [comment]
Please upload blend file

**Comment by Arazrajabi** [comment]
https://drive.google.com/file/d/1RKYzaowy10HpaLsTm8twZGw4pk8QU5mF/view?usp=sharing


Please try exporting static props with material (glb, fbx, obj, gltf ,....)

**Comment by Arazrajabi** [comment]
> Please upload blend file

https://drive.google.com/file/d/1RKYzaowy10HpaLsTm8twZGw4pk8QU5mF/view?usp=sharing

Please try exporting static props with materials (fbx,obj,gltf ,...)

**Comment by REDxEYE** [comment]
Ah, that's an interesting bug on both blender and sourceio sides :D
Update to https://github.com/REDxEYE/SourceIO/archive/refs/heads/master.zip this version, i fixed this bug on sourceio sides

**Comment by Arazrajabi** [comment]
![IMG_20231013_180208_507](https://github.com/REDxEYE/SourceIO/assets/147825377/595fcc85-c129-4125-8543-dc2c7b3a780b)
Could you export statics props with material? Or do you see material for static props in shading tab? I installed the addon from the link that you sent but nothing changed. As you see there is nothing in shading tab 

> Ah, that's an interesting bug on both blender and sourceio sides :D Update to https://github.com/REDxEYE/SourceIO/archive/refs/heads/master.zip this version, i fixed this bug on sourceio sides

**Comment by REDxEYE** [comment]
It's because these objects are collection instances

**Comment by REDxEYE** [comment]
They only render attached collection
If you want to export them, select everything and use "make instances real" operator

**Comment by Arazrajabi** [comment]
> They only render attached collection If you want to export them, select everything and use "make instances real" operator

I searched tutorials for the things that you told. But I couldn't understand them, they don't work with this projec can you tell more details about how to export these static props? Thanks

**Comment by Arazrajabi** [comment]
> They only render attached collection If you want to export them, select everything and use "make instances real" operator

I did it, now They have material. But still exported file hasn't proper texture. Exported file is exactly looks like solid mode in blender . It has material but wrong material

**Comment by Arazrajabi** [comment]
> > They only render attached collection If you want to export them, select everything and use "make instances real" operator
> 
> I did it, now They have material. But still exported file hasn't proper texture. Exported file is exactly looks like solid mode in blender . It has material but wrong material

As you mentioned discord. Disabling bvlg solved the problem
