### ISSUE TITLE
Python errors when attempting to install

### ISSUE THREAD

**Issue by Clanks00M** [REDxEYE/SourceIO#238]
![Screenshot (131)](https://github.com/REDxEYE/SourceIO/assets/149522195/ae0cfaed-3f9e-49ad-8b2f-512859e1ba95)

I'm not a coding guy, so I have no clue what might be causing this. Help? Thanks in advance.

**Comment by REDxEYE** [comment]
Disabled addon, restart blender and then you can delete it

**Comment by REDxEYE** [comment]
Blender/windows bug

**Comment by Clanks00M** [comment]
Ok it installed now. Thanks. :)
