### ISSUE TITLE
need help importing cs2 maps

### ISSUE THREAD

**Issue by IdontHaveAnIdeaAndEctroIstaken** [REDxEYE/SourceIO#239]
so i want to import de_nuke but i don't really know how can i do it, can anybody help with that?

also i dont know how to mount assets from games

**Comment by REDxEYE** [comment]
Similar applies to source2 https://youtu.be/aoL0q_J7Sf4?si=-61J8TcRwTI07R07
In source2 map geometry is made out of static props

**Comment by IdontHaveAnIdeaAndEctroIstaken** [comment]
thanks
