### ISSUE TITLE
VMTs dont import with model

### ISSUE THREAD

**Issue by MLSp3nce** [REDxEYE/SourceIO#24]
I have tested 3.5.5 and it seems as if the ability to import textures with it doesnt work, i tried it with multiple models (from badasses and a couple other ones like bendy) and not a single one worked! Idk if this is just unfinished or if its a bug but uh yeah

**Comment by REDxEYE** [comment]
This feature is WIP, I'll add more logs later, so i can track what happening inside

**Comment by ssllav** [comment]
Try:
Step 1. Import VMT firstly
Step 2. Import model

But have some issue - example if model have outfit, or hair with long tail. (Rosie Cop) material node for cop outfit and tail was not added. Need more test.

**Comment by MLSp3nce** [comment]
Tried that @sslav, doesnt work.

**Comment by MLSp3nce** [comment]
Tried that @sslav, doesnt work.
