### ISSUE TITLE
not so import import

### ISSUE THREAD

**Issue by derpimusprime** [REDxEYE/SourceIO#244]
i didn't work
![Screenshot 2023-11-22 223218](https://github.com/REDxEYE/SourceIO/assets/151806478/9022beb0-f644-41e1-bd66-7b23bf955de5)

**Comment by REDxEYE** [comment]
Missing .VTX file. Make sure that all 3 model component files are present: .mdl, .vvd, .vtx. Without all 3 you wont be able to import model
