### ISSUE TITLE
Can't enable the add-on

### ISSUE THREAD

**Issue by sumdudinhell** [REDxEYE/SourceIO#247]
I downloaded the add-on's zip file and installed it by Edit > Preferences > Add-ons > Install . When I tried to enable the extension, I get a whole bunch of errors:
![screen](https://github.com/REDxEYE/SourceIO/assets/152049532/f22574bd-6a2d-4a10-a008-0f43431844e5)
As far as i'm aware, these mean a missing file, but I can't seem to find it inside the .zip file.
Blender version: 3.0.1
Installed from KDE Discover
Operating system (I don't think it matters but here it is anyway): Lubuntu 22.04 LTS
Maybe this add-on only works with Windows? In that case i'll need to run Blender through wine.
Thanks in advance.

**Comment by sumdudinhell** [comment]
Using a more recent Blender version fixes the issue

**Comment by MrMage750** [comment]
> Using a more recent Blender version fixes the issue

using 4.0.2, the latest version, and it still doesn't work...

**Comment by REDxEYE** [comment]
@MrMage750 SourceIO 5.2.0 does not support blender 4.x.x. Use latest commit with Blender 4.x.x
