### ISSUE TITLE
Goldsrc texlights produce no light

### ISSUE THREAD

**Issue by Cianez** [REDxEYE/SourceIO#248]
I don't know if this is not working or was simply not planned, but it would be really nice to have texlights converted as emissive, if possible.
A lot of expert mappers refrain from using light entities nowadays and use texlights instead because they're more accurate and require no more than 1 point entity; which is definitely preferable considering the engine's limitations (that instead of having 20 or 30 light entities, you just need 1 entity to produce lights from 20 or 30 different faces).

**Comment by REDxEYE** [comment]
emissive polygons require correct rad file

**Comment by Cianez** [comment]
> emissive polygons require correct rad file
You mean that there's no info about texlights in the compiled BSP? Where can I get this rad file?

**Comment by Cianez** [comment]
> No, there is no light info in map. Only precompiled lightmaps

That's true, although there's the info_texlights point entity that stores textures and light amount data, which I believe it's how you get the light data from light and light_spot entities, right? I could be wrong, I'm just assuming.
![immagine](https://github.com/REDxEYE/SourceIO/assets/46445923/29fca5b3-e3e3-49d6-a1f6-825f31bcd4b3)

**Comment by REDxEYE** [comment]
That's where rad file comes in. It contains emissive power for each texture

**Comment by Cianez** [comment]
> That's where rad file comes in. It contains emissive power for each texture

How do you manage to import light data from light entities then? Also if we need this rad file, maybe we can just import it into Blender using your plugin if that's the case, I just don't know where to find it or how to generate it.

**Comment by Cianez** [comment]
> I got rad file from my friend, who re-created it. But its not very accurate

Do you mind sharing the process of creating one? I'm also trying to import a map of my own in Blender, which means I have all the project files, in case those are necessary. Also feel free to continue this in Discord if you don't want to go too much off-topic in here, my Discord name is the same as here but with no capital letters (cianez).

**Comment by REDxEYE** [comment]
You can join SourceIO discord server
