### ISSUE TITLE
Error when loading .vtf and .vmt

### ISSUE THREAD

**Issue by Leroymilo** [REDxEYE/SourceIO#251]
So, I know close to nothing about blender, so I might just be using it wring but the use case of vtf file conversion has no real tutorial. My goal is to convert the textures from [this](https://gamebanana.com/mods/383184) to .png, and this Blender addon is the only solution I seem to have on Linux... (no VTFEdit, and I'm not going back to the rabbit hole that is Wine).

After installing this plugin, I tried to import directly a .vtf downloaded from the link given above, but nothing happens, I guess it's because it's not possible to import a straight up texture to blender? But some of the .vmt from the same source I tried to import into blender gave me this error : 
![image](https://github.com/REDxEYE/SourceIO/assets/88249282/72b68cfc-62b0-473d-9d73-6541d6d23f32)

Is there a way to convert .vtf to .png through this blender addon?

**Comment by REDxEYE** [comment]
Blender 4.0 is not supported on SourceIO 5.2.0. either downgrade to blender 3.6 or use SourceIO from master branch
