### ISSUE TITLE
addon won't enable on 4.0

### ISSUE THREAD

**Issue by MrMage750** [REDxEYE/SourceIO#252]
using the latest version of the addon (5.2.0 ((I think?)) and the latest version of blender (4.0.2), attempting to enable the addon results in this error
![Blender Preferences 12_9_2023 7_49_15 PM](https://github.com/REDxEYE/SourceIO/assets/125535499/45575bef-c64f-4b73-87a9-339477cc89ff)

**Comment by REDxEYE** [comment]
SourceIO 5.2.0 does not support blender 4.x.x. Use latest commit with Blender 4.x.x
And looks like you installed addon a wrong way. Make sure zip file is named strictly `SourceIO.zip`, not SourceIO (1).zip.

**Comment by MrMage750** [comment]
> SourceIO 5.2.0 does not support blender 4.x.x. Use latest commit with Blender 4.x.x And looks like you installed addon a wrong way. Make sure zip file is named strictly `SourceIO.zip`, not SourceIO (1).zip.

so if 5.2.0 isn't the latest version, what is? because I don't see any commits of a later version, and I'm pretty sure sourceio master isn't what I'm looking for

**Comment by MrMage750** [comment]
turns out it was the sourceio master, because everything's working like it should, sorry for the misunderstanding

**Comment by REDxEYE** [comment]
This issue will permanently fixed in next release
