### ISSUE TITLE
Trying to import L4D2 weapons throws up error

### ISSUE THREAD

**Issue by Fizzvipop** [REDxEYE/SourceIO#253]
This was on Blender version 4.0
![Screenshot 2024-01-13 030318](https://github.com/REDxEYE/SourceIO/assets/141398914/de640b06-3ae9-41b9-8e4c-1129cbd17722)

**Comment by REDxEYE** [comment]
Something is wrong with MDL file. It begin with something that is not IDST. MDL files **must** begin with IDST, check what file are you importing

**Comment by Fizzvipop** [comment]
Its (I think) the world model for the chainsaw
