### ISSUE TITLE
unable to enable addon in 3.6, 4.0

### ISSUE THREAD

**Issue by loicbramoulle** [REDxEYE/SourceIO#254]
I checked that my blender.exe hasn't been renamed.
here is the error:
![image](https://github.com/REDxEYE/SourceIO/assets/49880198/149c1a6a-a4df-46b2-b486-56d6c89582a4)

**Comment by REDxEYE** [comment]
Make sure addon zip file does not have any additions to it's name. It should be named as SourceIO.zip

**Comment by loicbramoulle** [comment]
Ow, for anyone as dumb as me, I downloaded the source file, instead of the first .zip file in the release section. 
Thanks a lot !
yes the name of the zip had a version number at the end instead of being just "SourceIO.zip"

**Comment by REDxEYE** [comment]
-master should still work, problem usually come from SourceIO-master (6).zip
