### ISSUE TITLE
Props do not properly load in

### ISSUE THREAD

**Issue by doonv** [REDxEYE/SourceIO#256]
Blender Version: 3.6.5 (Flatpak)
OS: Kubuntu 23.10

I tried loading `ctf_2fort.bsp` from Team Fortress 2, but some props didn't load in. There is supposed to be a dark blue wall prop here but it's not there.
![image](https://github.com/REDxEYE/SourceIO/assets/58695417/47bea45a-7057-4115-9692-497c70283a22)
I have checked all the boxes when importing the map.

**Comment by REDxEYE** [comment]
Props are imported in separate process
Check wiki folder in repo

**Comment by doonv** [comment]
The wiki says

> click "Load entities" in SourceIO panel

Where is that SourceIO panel?

**Comment by REDxEYE** [comment]
Select entity object first
Then panel on right would showup

**Comment by doonv** [comment]
Where? 
![image](https://github.com/REDxEYE/SourceIO/assets/58695417/f74ebac3-26d8-41da-a589-05dafb2b739d)

**Comment by REDxEYE** [comment]
![image](https://github.com/REDxEYE/SourceIO/assets/17544576/7e553c85-b841-4a01-a901-133a31e6775b)

**Comment by doonv** [comment]
Oh...

**Comment by doonv** [comment]
It works! Tysm!
![image](https://github.com/REDxEYE/SourceIO/assets/58695417/722db9f5-2855-40f8-a894-f2bc58c4fbd7)
