### ISSUE TITLE
Session Import

### ISSUE THREAD

**Issue by MainarArts** [REDxEYE/SourceIO#26]
The SFM session import of the addon seems to be not working at all. I tried it with a session with only one model in it and no map selected but I always get the same error. I'm not sure if this error is on my side or the addon isn't working as it should be, so I'm asking you if you could maybe take a look at that once you have the time for it.

Thanks in advance.

**Comment by 0Curtain0** [comment]
@MainarArts I might be wrong but I believe DMX/Session imports are still in the experimental phase. 
At the moment, I think only MDL and VTF imports are currently working.
