### ISSUE TITLE
addon crashes when trying to load other entity

### ISSUE THREAD

**Issue by NandukYT** [REDxEYE/SourceIO#260]
![Screenshot_4](https://github.com/REDxEYE/SourceIO/assets/115937529/aa5716b5-dbaf-4508-b150-e8245df930d8)

I was trying to load the entites (Empties) in blender and after one empty the addon crashed. I will show it in this video and screen shot

https://github.com/REDxEYE/SourceIO/assets/115937529/c6badd2c-b9c2-4d48-ab87-47a52d5a1237

**Comment by 4rtb** [comment]
https://drive.google.com/drive/folders/1yf4j50uqaX9pPutNC-PVvhBusESZOgW5?usp=sharing

**Comment by REDxEYE** [comment]
Issue was caused by not very valid model. One of it's bone had empty name

**Comment by REDxEYE** [comment]
Fixed
