### ISSUE TITLE
How to load textures

### ISSUE THREAD

**Issue by 4rtb** [REDxEYE/SourceIO#261]
As you can see from the screenshot the all resources are loaded but there is no textures even with all downloaded add-ons for source film maker. How can I fix this? I followed the instructions from this video: https://www.youtube.com/watch?v=aoL0q_J7Sf4

Blend file: https://www.mediafire.com/file/7i7a5q5np7yau1v/untitled.blend/file (its the same as in my past report)

P.S. I imported map from gmod addon (bsp file)

![Screenshot_5](https://github.com/REDxEYE/SourceIO/assets/141040913/c60350c5-77a0-49fb-a213-204d7a775625)
![Screenshot_7](https://github.com/REDxEYE/SourceIO/assets/141040913/09204112-bef4-4803-be2a-e0ff66bc069a)

**Comment by REDxEYE** [comment]
Still reproducible?

**Comment by 4rtb** [comment]
Yes

**Comment by REDxEYE** [comment]
Provide more info about map, game and etc

**Comment by REDxEYE** [comment]
In blend file you uploaded all textures are present. Have you tried switching to material preview mode?

**Comment by 4rtb** [comment]
Nvm. This was my mistake, since I had already received textures for the house (these are just colors, for example red) (there are no complex textures in the game itself for them).
