### ISSUE TITLE
source.io "can not contain null bytes" error

### ISSUE THREAD

**Issue by wholuigi** [REDxEYE/SourceIO#264]
Every time I go to turn the addon onI get a trace back error that says "source code string cannot contain nullbytes" I need help.
![Screenshot 2024-03-04 162602](https://github.com/REDxEYE/SourceIO/assets/162224039/cf610302-a8f8-4658-bd16-078b951c5a1a)

**Comment by REDxEYE** [comment]
something is wrong with blender.

**Comment by REDxEYE** [comment]
Try reinstalling blender

**Comment by wholuigi** [comment]
I'll try that

**Comment by wholuigi** [comment]
It worked, that's so much.
