### ISSUE TITLE
Missing part of the map (TF2 Maps)

### ISSUE THREAD

**Issue by Ranily57** [REDxEYE/SourceIO#267]
![image](https://github.com/REDxEYE/SourceIO/assets/62222362/b6c53fd2-3a41-4c10-9802-62bf5708a313)

I think the script doesn't import props, because there is no models with it 
![image](https://github.com/REDxEYE/SourceIO/assets/62222362/cf3d4f1f-325d-4702-b3df-19d70c1866c3)

![image](https://github.com/REDxEYE/SourceIO/assets/62222362/95d8842f-402d-40d7-a56f-038e995b6e44)

It still 2Fort from the official BSP file on TF2 Folder (btw thx for the Blender 4.x update)

**Comment by REDxEYE** [comment]
https://github.com/REDxEYE/SourceIO/wiki/Entity-import-procedure
