### ISSUE TITLE
moving sfm download directory via steam breaks addon

### ISSUE THREAD

**Issue by MrMage750** [REDxEYE/SourceIO#269]
since I moved my sfm download directory to my C drive for logistical purposes, SourceIO has really been acting up with several problems. attempting to load any prop gives this error
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,

FileNotFoundError: [Errno 2] No such file or directory: 'D:\\SteamLibrary\\steamapps\\common\\SourceFilmmaker\\game\\bladesymphony\\gameinfo.txt'

whilst attempting to remove the addon (in order to try reinstalling) gives this

PermissionError: [WinError 5] Access is denied: 'C:\\Users\\Owner\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons\\SourceIO-master\\library\\utils\\pylib\\win\\pylib.dll'
Error: Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\shutil.py", line 618, in _rmtree_unsafe
    os.unlink(fullname)

from what little I know on the former, SourceIO might be struggling to detect the new locations of my source engine assets. the latter, I can only guesstimate and say that SFM SourceIO and blender are all conflicting with each other

**Comment by REDxEYE** [comment]
SourceIO stores mounted content inside of blend file in the section called mounted resources. If you moved them you need to update paths to resources. To delete addon, first disable it and restart blender, then you can remove it

**Comment by MrMage750** [comment]
turns out that was my problem, after poking around and opening SFM I noticed that there were all kinds of other things that had to be done, now that I have, SourceIO is working again
