### ISSUE TITLE
CS2 UV maps differ from imported textures

### ISSUE THREAD

**Issue by robbymanis** [REDxEYE/SourceIO#272]
blender 4.0
sourceIO 5.3.0

Imported models appear to have different UV maps then their textures 

example: 
`materials/models/weapons/customization/paints/custom/workshop/ssg08_fever_dream_tga_761ab14f.vtex_c`
`weapons/models/ssg08/weapon_snip_ssg08.vmdl_c`

![Screenshot 2024-03-28 at 6 41 39 PM](https://github.com/REDxEYE/SourceIO/assets/144573812/3c988e3e-946c-4906-ae83-0a65ce81ff99)
![Screenshot 2024-03-28 at 6 41 19 PM](https://github.com/REDxEYE/SourceIO/assets/144573812/38caa754-a911-4d8c-8d14-08d598a92352)

**Comment by REDxEYE** [comment]
Skins may use a second UV layer

**Comment by REDxEYE** [comment]
I have no idea how skins work.

**Comment by REDxEYE** [comment]
Ah, i see. Skins are for legacy weapons

**Comment by REDxEYE** [comment]
![image](https://github.com/REDxEYE/SourceIO/assets/17544576/03cc13ae-ab1f-4665-8c84-ad1a8421a724)
