### ISSUE TITLE
$DetailBlendMode0 - Better Method

### ISSUE THREAD

**Issue by hisprofile** [REDxEYE/SourceIO#276]
As per the [wiki on detail blend modes](https://developer.valvesoftware.com/wiki/$detail), any detail texture given blend mode 0 will darken and lighten the base texture. Values below 128 will darken, and values above 128 will lighten. 128 (0.5) is a middle ground which does nothing.

The best way to approach blend mode 0 is by multiplying the detail texture by two, then multiply it with the base texture.

Reference
![image](https://github.com/REDxEYE/SourceIO/assets/41131633/0db26ac2-8f62-4d5a-b5c9-bd7f7435b94a)

New method
![image](https://github.com/REDxEYE/SourceIO/assets/41131633/84bd1212-8d91-45ba-a74b-44fc64804744)

Old method
![image](https://github.com/REDxEYE/SourceIO/assets/41131633/75d14662-6c99-4881-ad41-108b7f6b044f)

**Comment by REDxEYE** [comment]
Why have you closed it?

**Comment by hisprofile** [comment]
because this has been implemented as of 5.4.0, it's no longer an issue
