### ISSUE TITLE
Missing instances in CS2

### ISSUE THREAD

**Issue by Devostated** [REDxEYE/SourceIO#278]
Some models instances are missing and spawn at 0 0 0
![image](https://github.com/REDxEYE/SourceIO/assets/30211694/d309c41a-a1d9-4424-8788-39fb888b7779)

I found them in the DATA section of the node000.vwnod_c with Source 2 Viewer.
Here is a JSON example of missing instances on Dust2 and their transformations. (Outdated names) 
```JSON
{
	"node000_prop0_lr0_agg375_2_dust_cart_color.vmdl": {
		"m_fragmentTransforms": [
			[-1.000000, 0.000000, 0.000000, 615.276001, -0.000000, -1.000000, 0.000000, 1812.390015, 0.000000, 0.000000, 1.000000, 562.596985],
			[1.000000, 0.000000, 0.000000, 984.000000, 0.000000, 1.000000, 0.000000, 1744.000000, 0.000000, 0.000000, 1.000000, 473.528992]
		],
		"m_renderableModel": "maps/de_dust2/worldnodes/node000_prop0_lr0_agg375_2_dust_cart_color.vmdl"
	},
	"node000_prop1_lr0_agg376_3_dust_wires_01.vmdl": {
		"m_fragmentTransforms": [
			[-0.000000, -1.000000, 0.000000, -368.000000, 1.000000, -0.000000, 0.000000, -356.000000, 0.000000, 0.000000, 1.000000, 140.000000],
			[0.000000, 0.000000, 1.000000, -389.000000, 0.000000, -1.000000, 0.000000, -360.000000, 1.000000, 0.000000, -0.000000, 157.000000],
			[0.000000, 0.000000, 1.000000, -389.000000, 0.000000, -1.000000, 0.000000, -360.000000, 1.000000, 0.000000, -0.000000, 222.000000]
		],
		"m_renderableModel": "maps/de_dust2/worldnodes/node000_prop1_lr0_agg376_3_dust_wires_01.vmdl"
	},
	"node000_prop2_lr0_agg377_10_dust_window_frame_wood_01.vmdl": {
		"m_fragmentTransforms": [
			[1.000000, 0.000000, 0.000000, -816.000000, 0.000000, 1.000000, 0.000000, -1040.000000, 0.000000, 0.000000, 1.000000, 680.000000],
			[1.000000, 0.000000, 0.000000, -816.000000, 0.000000, 1.000000, 0.000000, -1040.000000, 0.000000, 0.000000, 1.000000, 360.000000],
			[1.000000, 0.000000, 0.000000, -816.000000, 0.000000, 1.000000, 0.000000, -1040.000000, 0.000000, 0.000000, 1.000000, 520.000000],
			[1.000000, 0.000000, 0.000000, -720.000000, 0.000000, 1.000000, 0.000000, -1040.000000, 0.000000, 0.000000, 1.000000, 520.000000],
			[1.000000, 0.000000, 0.000000, -720.000000, 0.000000, 1.000000, 0.000000, -1040.000000, 0.000000, 0.000000, 1.000000, 360.000000],
			[1.000000, 0.000000, 0.000000, -720.000000, 0.000000, 1.000000, 0.000000, -1040.000000, 0.000000, 0.000000, 1.000000, 680.000000],
			[1.000000, 0.000000, 0.000000, -416.000000, 0.000000, 1.000000, 0.000000, -1040.000000, 0.000000, 0.000000, 1.000000, 680.000000],
			[1.000000, 0.000000, 0.000000, -416.000000, 0.000000, 1.000000, 0.000000, -1040.000000, 0.000000, 0.000000, 1.000000, 520.000000],
			[1.000000, 0.000000, 0.000000, -416.000000, 0.000000, 1.000000, 0.000000, -1040.000000, 0.000000, 0.000000, 1.000000, 360.000000],
			[0.000000, 1.000000, 0.000000, -512.000000, -1.000000, 0.000000, 0.000000, -457.000000, 0.000000, 0.000000, 1.000000, 499.000000]
		],
		"m_renderableModel": "maps/de_dust2/worldnodes/node000_prop2_lr0_agg377_10_dust_window_frame_wood_01.vmdl"
	},
	"node000_prop3_lr0_agg378_1_dust_satellite_dish_color.vmdl": {
		"m_fragmentTransforms": [
			[0.358368, 0.933581, 0.000000, 712.000000, -0.933581, 0.358368, 0.000000, 2036.000000, 0.000000, 0.000000, 1.000000, 576.000000]
		],
		"m_renderableModel": "maps/de_dust2/worldnodes/node000_prop3_lr0_agg378_1_dust_satellite_dish_color.vmdl"
	},
	"node000_prop4_lr0_agg379_10_hr_dust_kasbah_merlon002_color.vmdl": {
		"m_fragmentTransforms": [
			[-1.000000, 0.000000, -0.000000, -301.972992, -0.000000, -0.999848, 0.017452, 1547.189941, 0.000000, 0.017452, 0.999848, 418.786011],
			[0.000000, 0.999848, -0.017452, -143.973007, -1.000000, 0.000000, -0.000000, 1547.189941, 0.000000, 0.017452, 0.999848, 418.786011],
			[-0.000000, -0.999848, 0.017452, -301.953003, 1.000000, -0.000000, 0.000000, 1703.219971, 0.000000, 0.017452, 0.999848, 418.786011],
			[-1.000000, 0.000000, -0.000000, -298.529999, -0.000000, -0.999848, 0.017452, 1810.449951, 0.000000, 0.017452, 0.999848, 418.786011],
			[-0.000000, -0.999848, 0.017452, -298.529999, 1.000000, -0.000000, 0.000000, 1968.449951, 0.000000, 0.017452, 0.999848, 418.786011],
			[-1.000000, 0.000000, -0.000000, -306.214996, -0.000000, -0.999848, 0.017452, 2318.659912, 0.000000, 0.017452, 0.999848, 445.786011],
			[-0.000000, -0.999848, 0.017452, -306.214996, 1.000000, -0.000000, 0.000000, 2476.659912, 0.000000, 0.017452, 0.999848, 445.786011],
			[-1.000000, 0.000000, -0.000000, -301.972992, -0.000000, -0.999848, 0.017452, 2988.189941, 0.000000, 0.017452, 0.999848, 509.786011],
			[-0.000000, -0.999848, 0.017452, -301.953003, 1.000000, -0.000000, 0.000000, 3144.219971, 0.000000, 0.017452, 0.999848, 509.786011],
			[0.000000, 0.999848, -0.017452, -143.973007, -1.000000, 0.000000, -0.000000, 2988.189941, 0.000000, 0.017452, 0.999848, 509.786011]
		],
		"m_renderableModel": "maps/de_dust2/worldnodes/node000_prop4_lr0_agg379_10_hr_dust_kasbah_merlon002_color.vmdl"
	},
	"node000_prop5_lr0_agg380_5_dust_kasbah_rooftrim_01.vmdl": {
		"m_fragmentTransforms": [
			[-0.000000, -1.000000, 0.000000, -2232.260010, 1.000000, -0.000000, 0.000000, 3975.639893, 0.000000, 0.000000, 1.000000, 996.997986],
			[-1.000000, 0.000000, 0.000000, -224.953003, -0.000000, -1.000000, 0.000000, 1629.219971, 0.000000, 0.000000, 1.000000, 419.786011],
			[0.000000, 1.000000, 0.000000, -224.529999, -1.000000, 0.000000, 0.000000, 1887.449951, 0.000000, 0.000000, 1.000000, 418.786011],
			[-0.000000, -1.000000, 0.000000, -224.184998, 1.000000, -0.000000, 0.000000, 2399.639893, 0.000000, 0.000000, 1.000000, 446.786011],
			[-1.000000, 0.000000, 0.000000, -224.953003, -0.000000, -1.000000, 0.000000, 3070.219971, 0.000000, 0.000000, 1.000000, 510.786011]
		],
		"m_renderableModel": "maps/de_dust2/worldnodes/node000_prop5_lr0_agg380_5_dust_kasbah_rooftrim_01.vmdl"
	},
	"node000_prop6_lr0_agg381_2_dust_wall_vents_01.vmdl": {
		"m_fragmentTransforms": [
			[-1.000000, 0.000000, 0.000000, -415.000000, -0.000000, -1.000000, 0.000000, -360.000000, 0.000000, 0.000000, 1.000000, 236.000000],
			[1.000000, 0.000000, 0.000000, -483.000000, 0.000000, 1.000000, 0.000000, -191.750000, 0.000000, 0.000000, 1.000000, 225.000000]
		],
		"m_renderableModel": "maps/de_dust2/worldnodes/node000_prop6_lr0_agg381_2_dust_wall_vents_01.vmdl"
	},
	"node000_prop7_lr0_agg382_2_dust_wire_attachments_01.vmdl": {
		"m_fragmentTransforms": [
			[-1.000000, 0.000000, 0.000000, -389.000000, -0.000000, -1.000000, 0.000000, -360.000000, 0.000000, 0.000000, 1.000000, 227.000000],
			[-0.000000, -1.000000, 0.000000, -368.000000, 1.000000, -0.000000, 0.000000, -363.000000, 0.000000, 0.000000, 1.000000, 139.507996]
		],
		"m_renderableModel": "maps/de_dust2/worldnodes/node000_prop7_lr0_agg382_2_dust_wire_attachments_01.vmdl"
	},
	"node000_prop8_lr0_agg383_1_dust_windows_01.vmdl": {
		"m_fragmentTransforms": [
			[0.000000, 1.000000, 0.000000, -512.000000, -1.000000, 0.000000, 0.000000, -457.000000, 0.000000, 0.000000, 1.000000, 499.000000]
		],
		"m_renderableModel": "maps/de_dust2/worldnodes/node000_prop8_lr0_agg383_1_dust_windows_01.vmdl"
	}
}
```

**Comment by REDxEYE** [comment]
Fragments are not yet implemented

**Comment by REDxEYE** [comment]
Will implement at some point

**Comment by Devostated** [comment]
Glad to hear that. Luckily I got a script to extract that stuff as JSON, but others will definitely benefit much more from that.

**Comment by REDxEYE** [comment]
I cannot find this fragments data in vnod file. Can you please provide more info?

**Comment by Devostated** [comment]
For example in the Dust2 node000.vwnod_c 
In DATA with Source 2 Viewer at line 82386 - 82723
m_fragmentTransforms = 
            [
                
                [
                    -1.000000,
                    0.000000,
                    -0.000000,
                    -301.972992,
                    -0.000000,
                    -0.999848,
                    0.017452,
                    1547.189941,
                    0.000000,
                    0.017452,
                    0.999848,
                    418.786011,
                ],
                
                [
                    0.000000,
                    0.999848,
                    -0.017452,
                    -143.973007,
                    -1.000000,
                    0.000000,
                    -0.000000,
                    1547.189941,
                    0.000000,
                    0.017452,
                    0.999848,
                    418.786011,
                ],
                
                [
                    -0.000000,
                    -0.999848,
                    0.017452,
                    -301.953003,
                    1.000000,
                    -0.000000,
                    0.000000,
                    1703.219971,
                    0.000000,
                    0.017452,
                    0.999848,
                    418.786011,
                ],
                
                [
                    -1.000000,
                    0.000000,
                    -0.000000,
                    -298.529999,
                    -0.000000,
                    -0.999848,
                    0.017452,
                    1810.449951,
                    0.000000,
                    0.017452,
                    0.999848,
                    418.786011,
                ],
                
                [
                    -0.000000,
                    -0.999848,
                    0.017452,
                    -298.529999,
                    1.000000,
                    -0.000000,
                    0.000000,
                    1968.449951,
                    0.000000,
                    0.017452,
                    0.999848,
                    418.786011,
                ],
                
                [
                    -1.000000,
                    0.000000,
                    -0.000000,
                    -306.214996,
                    -0.000000,
                    -0.999848,
                    0.017452,
                    2318.659912,
                    0.000000,
                    0.017452,
                    0.999848,
                    445.786011,
                ],
                
                [
                    -0.000000,
                    -0.999848,
                    0.017452,
                    -306.214996,
                    1.000000,
                    -0.000000,
                    0.000000,
                    2476.659912,
                    0.000000,
                    0.017452,
                    0.999848,
                    445.786011,
                ],
                
                [
                    -1.000000,
                    0.000000,
                    -0.000000,
                    -301.972992,
                    -0.000000,
                    -0.999848,
                    0.017452,
                    2988.189941,
                    0.000000,
                    0.017452,
                    0.999848,
                    509.786011,
                ],
                
                [
                    -0.000000,
                    -0.999848,
                    0.017452,
                    -301.953003,
                    1.000000,
                    -0.000000,
                    0.000000,
                    3144.219971,
                    0.000000,
                    0.017452,
                    0.999848,
                    509.786011,
                ],
                
                [
                    0.000000,
                    0.999848,
                    -0.017452,
                    -143.973007,
                    -1.000000,
                    0.000000,
                    -0.000000,
                    2988.189941,
                    0.000000,
                    0.017452,
                    0.999848,
                    509.786011,
                ],
            ]
            m_renderableModel = resource:"maps/de_dust2/worldnodes/node000_prop4_lr0_agg376_10_hr_dust_kasbah_merlon002_color.vmdl"
        },

**Comment by REDxEYE** [comment]
I think i found it

**Comment by REDxEYE** [comment]
Done, please test

**Comment by Devostated** [comment]
Looks great on first sight!
