### ISSUE TITLE
trying to import a mdl file and this error pops up

### ISSUE THREAD

**Issue by Nexusmarco** [REDxEYE/SourceIO#279]
![image](https://github.com/REDxEYE/SourceIO/assets/166840256/37fd7ff4-356b-4f9c-a6a5-9ae02277f69d)
![image](https://github.com/REDxEYE/SourceIO/assets/166840256/b6912d94-6ee1-497a-8094-c6bcbbd1e1bf)

Python: Traceback (most recent call last):
  File "C:\Users\marie\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\operators\source1_operators.py", line 54, in execute
    put_into_collections(model_container, mdl_path.stem, bodygroup_grouping=self.bodygroup_grouping)
  File "C:\Users\marie\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SourceIO\blender_bindings\models\common.py", line 57, in put_into_collections
    if model_container.bodygroups:
AttributeError: 'NoneType' object has no attribute 'bodygroups'

**Comment by REDxEYE** [comment]
Please, upload mdl file

**Comment by Nexusmarco** [comment]
I'm sorry but the person that gave me the file told me to not share it with anyone

**Comment by REDxEYE** [comment]
Cant help you without the ability to troubleshoot. 
You can send me private message with model on discord

**Comment by Nexusmarco** [comment]
okay

**Comment by Oceanman10** [comment]
I am having the same issue with importing any of the scientists from Half Life. I would upload the file but github does not support mdl files.

**Comment by REDxEYE** [comment]
Issue was caused by missing required model files, such as .vvd and .vtx files
