### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by Bouh** [REDxEYE/SourceIO#28]
Hello

Can you provide a list of formats openable with this addons ?
And what is supported by your addon ?
I see mesh, armature and lod ?

Thank you

**Comment by REDxEYE** [comment]
Source1: .vtf, .vmt(WIP), .mdl, .bsp(planned)
Source2: .vtex(will be soon), .vmat(planned), .vmdl(WIP)

**Comment by REDxEYE** [comment]
vtex support were added in latest version
