### ISSUE TITLE
Import Source2 VMDL throws error

### ISSUE THREAD

**Issue by Coolchouzhao** [REDxEYE/SourceIO#280]
![image](https://github.com/REDxEYE/SourceIO/assets/91487657/facf4360-104f-47a2-ba3a-96fa1ad9f056)

the error above is all i get when trying to import .vmdl_c files

**Comment by REDxEYE** [comment]
https://github.com/REDxEYE/SourceIO/releases/tag/5.3.0

**Comment by Coolchouzhao** [comment]
> https://github.com/REDxEYE/SourceIO/releases/tag/5.3.0

![image](https://github.com/REDxEYE/SourceIO/assets/91487657/d912174a-2abf-41f7-bbab-59818fc606a3)
I do have the 5.3.0 version

**Comment by REDxEYE** [comment]
Fixed release. It had wrong zip uploaded
