### ISSUE TITLE
Early Source 2 models cannot be imported

### ISSUE THREAD

**Issue by Teajai2** [REDxEYE/SourceIO#283]
In the earliest manifests for SteamVR's now-defunct Performance Test, there exists several models made in the infancy of the Source 2 engine that cannot seem to be imported to Blender via SourceIO. Whenever I try, I get this error code:

```
Python: Traceback (most recent call last):
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\operators\source2_operators.py", line 55, in execute
    container = load_model(model_resource, self.scale, self.lod_mask,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\source2\vmdl_loader.py", line 78, in load_model
    objects = create_meshes(resource, ContentManager(), container, scale, lod_mask, import_attachments)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\source2\vmdl_loader.py", line 172, in create_meshes
    sub_meshes = load_external_mesh(model_resource, cm, container, scale, i, mesh_resource, import_attachments)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teajai\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\SourceIO-master\blender_bindings\source2\vmdl_loader.py", line 205, in load_external_mesh
    if morph_set_path := data_block['m_morphSet']:
                         ~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'm_morphSet'
```
[Source 2 Viewer,](https://valveresourceformat.github.io/) another program that allows for the viewing and manipulation of Source 2 content, has a similar error when trying to import some of these earliest models.

The early SteamVR Manifest with the problem models can be found [here.](https://archive.org/details/robot-repair.-7z) Some of the models in question that do not work are: 
* app_323910/depot_323911/vr/models/dog.vmdl_c
* app_323910/depot_323911/vr/models/antlion.vmdl_c
* app_323910/depot_323911/vr/models/glados/glados_model.vmdl_c

**Comment by REDxEYE** [comment]
Should be fixed in 5d498ee

**Comment by REDxEYE** [comment]
Please check

**Comment by Teajai2** [comment]
I can confirm that it works! Thank you so much!
![image](https://github.com/REDxEYE/SourceIO/assets/95593217/434d89f2-9ffc-461f-a327-2b09ade98e13)

**Comment by REDxEYE** [comment]
Also, what a coincident, i also have X-Ray engine addon installed :D. Been messing around SoC
