### ISSUE TITLE
Vertex Colors/Color Attributes of CS2 Maps not loaded??

### ISSUE THREAD

**Issue by FersyVR** [REDxEYE/SourceIO#284]
Maps don't seem to have color attributes which makes vertex blending impossible for my shader.

I heard older builds were able to have color attributes. 

Here a screenshot of dust2 with shading and color attributes selected:
![image](https://github.com/REDxEYE/SourceIO/assets/52735241/93790851-8de1-47b0-b2ca-3823d8fa9fed)

**Comment by REDxEYE** [comment]
I'll take a look

**Comment by FersyVR** [comment]
any luck?

**Comment by REDxEYE** [comment]
In some cases valve stores vertex colors as UV (probably because they only needed 2 channels instead of 4), so please check `TEXCOORD_4` UV layer, usually it is a vertex color buffer
