### ISSUE TITLE
Dark splotches appear on imported GoldSrc model

### ISSUE THREAD

**Issue by Teajai2** [REDxEYE/SourceIO#286]
As of the latest dev commit (4830d8a), GoldSrc models seem to have dark splotches appearing on them. This appears to be a problem with how the mesh is imported, rather than the textures themselves, because these dark splotches also appear in untextured views. SourceIO does not spit out any errors when importing a model.

### (Left is model imported by SourceIO w/ 1.0 world scale, right is .smd imported with Blender Source Tools and textured manually.)
![image](https://github.com/REDxEYE/SourceIO/assets/95593217/b9a441e8-7f31-4617-b8f1-8b0b4066c24c)
![image](https://github.com/REDxEYE/SourceIO/assets/95593217/f0862d79-e5b4-430e-b7ee-e069321f651d)

**Comment by REDxEYE** [comment]
This is caused by wrong normals. I'll take a look

**Comment by REDxEYE** [comment]
![image](https://github.com/REDxEYE/SourceIO/assets/17544576/8757e0d2-0f92-4863-b036-02ac6b5665a4)
Just tested on my dev version, I'm unable to reproduce
