### ISSUE TITLE
Half-Life: Blue Shift maps not compatible with SourceIO import

### ISSUE THREAD

**Issue by Teajai2** [REDxEYE/SourceIO#289]
The maps from _Half-Life: Blue Shift_ are not compatible with SourceIO. This is because Gearbox modified the .bsp format that Blue Shift maps used, thus resulting in incompatibility with map decompilers and viewers. There are a couple of programs that are capable of fixing the issue by converting the maps into the standard .bsp format (i.e. [bspfix](https://valvedev.info/tools/bspfix/)), but I am unaware of any programs like these that have publicly accessible source code.

Here's a small sample size of Blue Shift maps, if that may be of help to you.
[Blue Shift Maps.zip](https://github.com/REDxEYE/SourceIO/files/15205454/Blue.Shift.Maps.zip)

**Comment by REDxEYE** [comment]
Fixed by 76ddb5b7
