### ISSUE TITLE
Plans for Exporting BSP Imports

### ISSUE THREAD

**Issue by trisasarex** [REDxEYE/SourceIO#295]
I need to export a Portal Map to OBJ or FBX but as I have read that it isn't planned.
It will help a lot if one of the developers plans it!
![image](https://github.com/REDxEYE/SourceIO/assets/115816685/85ee2ba5-fc42-41e4-b7eb-7b9837916fa8)

**Comment by REDxEYE** [comment]
Export back into BSP isn't planned, however you can export into any format you want using other plugins
