### ISSUE TITLE
Mesh Auto smooth error

### ISSUE THREAD

**Issue by AriaRGB** [REDxEYE/SourceIO#305]
Apparently the newest version of blender has removed calling for the attribute "autosmooth" I don't know how true this is but it seems like there is some proof to back it up since export_smd.py get caught on it, [Here](https://blender.stackexchange.com/questions/316696/attributeerror-mesh-object-has-no-attribute-use-auto-smooth/319224#319224) is a new fix for it using autosmooth as a modifier.
![image_2024-06-23_173322872](https://github.com/REDxEYE/SourceIO/assets/91868169/79dd2ce2-d255-44f3-8bc9-433a82a87cdb)

**Comment by AriaRGB** [comment]
Yeah it's definitely blender 4.1.1, I downgraded my blender version and addon and it worked fine

**Comment by REDxEYE** [comment]
It fixed in 5.4.0
