### ISSUE TITLE
Source 1 displacement UVs are ~2 times bigger after import

### ISSUE THREAD

**Issue by EntityinArray** [REDxEYE/SourceIO#308]
Hello, thank you for inventing and working on this amazing tool!

Blender 4.1
SourceIO 5.4.1
Windows 10

After importing a Source 1 map, displacement UVs appear to be roughly 2 times bigger than in-game

Here's an example on surf_mesa
In-game (Garry's Mod):
![image](https://github.com/REDxEYE/SourceIO/assets/18554021/31a6c54b-fd24-494a-b57d-ee0455b75dc0)
Blender 4.1:
![image](https://github.com/REDxEYE/SourceIO/assets/18554021/2dd3355c-41f7-46c2-be7e-6bec9a0d1949)

Wish you a great day, thanks again!

**Comment by REDxEYE** [comment]
Check if they have scaling in vmt material
