### ISSUE TITLE
Trying to import cs_office.vpk but the textures say "error creating file" when trying to unpack them

### ISSUE THREAD

**Issue by Tivantri** [REDxEYE/SourceIO#309]
I'm using version 5.4.1 of SourceIO and 3.4 of Blender
![image_2024-07-10_024520151](https://github.com/REDxEYE/SourceIO/assets/174408694/b2b7d6c1-e56b-444f-9cb4-febb515489ac)

**Comment by Tivantri** [comment]
All the materials are either purple, green or blue

**Comment by Tivantri** [comment]
Would I need Plumber for that? Sorry, I'm very new to this

**Comment by REDxEYE** [comment]
No, SourceIO is self sufficient

**Comment by REDxEYE** [comment]
Closing since this is blenders error saving file, not sourceio
