### ISSUE TITLE
Importing models into Blender 4.2 are metallic for some reason

### ISSUE THREAD

**Issue by Bassquake** [REDxEYE/SourceIO#310]
As an example, importing metal_box.mdl from Portal 1 (unpacked using Crowbar 0.74) looks like this:

![metal_box](https://github.com/user-attachments/assets/54474a2e-44f3-4ee2-b840-5d04877ae29f)

These are the Shading settings:

![metal_box_shadings](https://github.com/user-attachments/assets/cfdc204e-5bfb-4b01-a85f-83aa16876ca6)

If I remove the Green to Metallic the model looks normal:

![metal_box_shadings_disable_metallic](https://github.com/user-attachments/assets/7209fcfd-446e-4216-a1a4-eb9e140abfed)

Its the same on any object I import in.

**Comment by REDxEYE** [comment]
Some engine branches use G channel as phong tint factor that's why it connected to metalic

**Comment by Bassquake** [comment]
> Some engine branches use G channel as phong tint factor that's why it connected to metalic

Ok, good to know. So by just disconnecting G to Metallic, the model is all fine to use?

**Comment by REDxEYE** [comment]
Yes
