### ISSUE TITLE
Importing Portal 2 mdls are metallic and messed up textures

### ISSUE THREAD

**Issue by Bassquake** [REDxEYE/SourceIO#311]
As title. After unpacking using Crobar 0.74 on Portal 2 and then Import into Blender 4.2, the objects are metallic and textures are wrong.

This is what it looks like importing metal_box.mdl from models/props:

![metal_box_portal_2](https://github.com/user-attachments/assets/e98a633d-30db-4ac8-a272-3694cf3f088c)

This is its shading settings:

![metal_box_shadings_portal_2](https://github.com/user-attachments/assets/f59c6dc2-d536-41c2-b8f4-c0869763e211)

Disconnecting Green to Metallic gets rid of the metal look but textures obviously still borked.

**Comment by REDxEYE** [comment]
![image](https://github.com/user-attachments/assets/e62243af-38eb-4bd3-ae8a-960a101da216)
Just tested in 3.6 and 4.2, textures import correctly. Make sure you're using latest version of SourceIO

**Comment by REDxEYE** [comment]
It's probably texture conflict. You did not delete old texture. Both game uses same texture name and path, so sourceio thought that texture was imported before and re-used old portal1 textures

**Comment by Bassquake** [comment]
Im using 5.4.3. Ive always used New to create a new scene in Blender so it shouldnt be using old texture though.

**Comment by REDxEYE** [comment]
Have you configured texture cache?

**Comment by Bassquake** [comment]
> Have you configured texture cache?

Where do I set that? Currently these are Blenders System settings:

![cache](https://github.com/user-attachments/assets/327b99c9-9b92-41e6-98ab-0f50b210d735)

**Comment by REDxEYE** [comment]
![image](https://github.com/user-attachments/assets/358a10f5-d30a-4d73-92e4-b06bbc582fba)

**Comment by Bassquake** [comment]
Mine was empty, so put in a path. Still have the same issue. Seems to keep reimporting the same Portal 1 and some other folders everytime. Clicking the X to Clean All Resources or - to Delete the folders in the list doesnt make a difference.

![cache-list](https://github.com/user-attachments/assets/77e478b3-771e-4ddb-a51d-a45e19e91012)

**Comment by Bassquake** [comment]
Uninstalled and reinstalled SourceIO and restarted Blender. I get just the one path showing now. But object is still not right.

![reinstalled](https://github.com/user-attachments/assets/9a5cf4f3-8b9e-4bce-a65e-bf45f2742aa7)

**Comment by REDxEYE** [comment]
No idea then

**Comment by Bassquake** [comment]
If I change the $basetexture to one of these, it looks ok. I guess Ill have to manually fix them as I go.

![textures-that-work](https://github.com/user-attachments/assets/884b9ed4-52a9-4b0f-aaaf-c2705170b9e9)

**Comment by REDxEYE** [comment]
Should be partially fixed now
