### ISSUE TITLE
Not working in blender 4.2 (release candidate)

### ISSUE THREAD

**Issue by dommy738** [REDxEYE/SourceIO#313]
When I download and install the add on my version of blender and try to enable it; it simply just says at "the module 'SourceIO' has no attribute registor". The error can be seen here
![image_2024-08-03_114708140](https://github.com/user-attachments/assets/340f115e-7495-4dc7-b4f8-6cc148cc13d2)

**Comment by REDxEYE** [comment]
Try re-downloading and re-installing addon. Usually it helps with this weird error

**Comment by BronyKing666-original** [comment]
I have no SourcIO.
