### ISSUE TITLE
Blender 4.2 crashing when trying to dissolve/delete vertices, faces, edges

### ISSUE THREAD

**Issue by TerryTheHorrible** [REDxEYE/SourceIO#314]
First i want to point out that im not very knowledgeble with Blender
I wanted to try myself by removing the coat from Deadlock's Paradox and extending her shirt arms underneath, but every time i try to dissolve anything blender just straight up crashes. I think it has something to do with the physics pointers, since it has some weird cloth references when you go in skeleton viewer in Source 2 viewer

Sorry if i left this issue in the wrong place 

blender crash log in case it helps
[blender.crash.txt](https://github.com/user-attachments/files/16589099/blender.crash.txt)

**Comment by REDxEYE** [comment]
It was recently fixed in [5.4.4](https://github.com/REDxEYE/SourceIO/tree/5.4.4) version

**Comment by TerryTheHorrible** [comment]
> It was recently fixed in [5.4.4](https://github.com/REDxEYE/SourceIO/tree/5.4.4) version

yep. Im terribly sorry.  I didnt pay attention and assumed it was a linux only build. It work flawlessly now
