### ISSUE TITLE
Static_props/dynamic_props problems with bones.

### ISSUE THREAD

**Issue by MichaelWitdah** [REDxEYE/SourceIO#315]
Imported the map from Portal 2 and there was a problem with the vault door, namely the location of the hinge that holds this door, is there any way to edit the bones of this prop to fix the situation? I'm just a teapot and I don't know how to do it.

Examples are shown in the first and second photo

Pic. 1
![blender_lQqSObqWEh](https://github.com/user-attachments/assets/378ad938-330c-4bdb-800b-873e1592ce65)
Pic. 2
![portal2_IAnERviFwo](https://github.com/user-attachments/assets/a048432b-33ea-49b3-89e0-e0ba4be8edba)

**Comment by REDxEYE** [comment]
Animated models will have problems as i didnt finish animation support

**Comment by MichaelWitdah** [comment]
> Animated models will have problems as i didnt finish animation support

Oh, I'll know, thanks for the reply.

**Comment by MichaelWitdah** [comment]
> Animated models will have problems as i didnt finish animation support

And one last question that worries me, is there any possibility to manipulate the polygons of static/dynamic props at all ? And is such an opportunity planned in the future ?

**Comment by REDxEYE** [comment]
You can use `make instances real` to replace instanced collection with actual mesh data
