### ISSUE TITLE
Static/dynamic props dont have textures if i export a model to other programs with embedded textures.

### ISSUE THREAD

**Issue by joemama0912** [REDxEYE/SourceIO#316]
I dont wanna assign textures by hand cause theres like 100 static/dynamic props in the map so

**Comment by REDxEYE** [comment]
Sorry, but that not a sourceio issue. Try unpacking all embedded textures and then exporting to format of choice

**Comment by joemama0912** [comment]
ill try that, thanks

**Comment by joemama0912** [comment]
didnt seem to work
are there any settings i should change when i press load entities to make it so the materials automatically are assigned in unity?
there are materials in unity for them but they dont have the textures assigned

**Comment by REDxEYE** [comment]
Again, it's not a SourceIO import problem. The only other suggestion is to try to import with texture sourceio cache set, it would make sourceio write files to disk immediately.

**Comment by REDxEYE** [comment]
![image](https://github.com/user-attachments/assets/297f7261-8c05-404f-88ae-e923b7e758ff)
