### ISSUE TITLE
What is the proper way to edit Master Instances?

### ISSUE THREAD

**Issue by EntityinArray** [REDxEYE/SourceIO#320]
Hi, thank you for this amazing addon.

SourceIO imports props and entities and puts them inside of a collection `MASTER_INSTANCES_DO_NOT_EDIT`
Is there a way to copy master instance into it's own independent thing for editing?
![image](https://github.com/user-attachments/assets/e9f7f7b4-9b39-4fb7-bce7-cf46450b767d)

**Comment by REDxEYE** [comment]
Ctrl+A -> make instances real
or
Just edit them in master instances collection, it would update all objects on scene.
