### ISSUE TITLE
Add Support for Deadlock?

### ISSUE THREAD

**Issue by Backxtar** [REDxEYE/SourceIO#328]
Jo guys :) 

is there any chance to improve the features of SourceIO for Deadlock?

**Comment by REDxEYE** [comment]
Deadlock is already supported

**Comment by Backxtar** [comment]
ah nice so no need to decompile files? Just export into a folder?

**Comment by REDxEYE** [comment]
Just import the map vpk file

**Comment by Backxtar** [comment]
uh great nice no need to export at all

**Comment by REDxEYE** [comment]
https://github.com/REDxEYE/SourceIO/wiki/How-to-import-entities You may also want to give this a quick read

**Comment by Backxtar** [comment]
is this also compat. with mac?

**Comment by REDxEYE** [comment]
Kind of. Native libraries for mac havent been updated in a while.

**Comment by Backxtar** [comment]
i mean this runs in python or? so it should be compat.

**Comment by REDxEYE** [comment]
SourceIO have couple of native libraries
https://github.com/REDxEYE/SourceIO/tree/master/library/utils/rustlib like this one
