### ISSUE TITLE
Blender 4.3 Completely broke material importing

### ISSUE THREAD

**Issue by VCSoldier** [REDxEYE/SourceIO#332]
Blender 4.3 seems to have completely broken material importing, regardless of what model i pick, i assume this is due to the python api changes they did

**Comment by REDxEYE** [comment]
Yes, 4.3 is not supported yet

**Comment by jerry-harm** [comment]
Is there any ideal about why this happend?

**Comment by REDxEYE** [comment]
I just said, blender 4.3 is not fully supported

**Comment by PixelTails** [comment]
has it been fixed yet?
