### ISSUE TITLE
Import animation with model eror

### ISSUE THREAD

**Issue by chykchaxx** [REDxEYE/SourceIO#333]
Hi I want to import a model with animation from HL 2 but I get an error, please help. 
![blender_ppgNmyf5Ba](https://github.com/user-attachments/assets/5fc4a4c3-9884-419d-8ab6-dc1f7a80c9d8)

**Comment by REDxEYE** [comment]
Animation support is not finished.

**Comment by chykchaxx** [comment]
😟
