### ISSUE TITLE
Materials Import Error

### ISSUE THREAD

**Issue by JialinClone** [REDxEYE/SourceIO#335]
Whenever I import an source material (vmt) it gives me an error, and the texture is completely black
![Zrzut ekranu 2024-11-27 111827](https://github.com/user-attachments/assets/c8ec0a89-18be-4aa7-93f6-f28640ebcc81)
![Zrzut ekranu 2024-11-27 111817](https://github.com/user-attachments/assets/78c41956-0d1c-41ab-9cfa-9287f8fd4aa5)

**Comment by MrMage750** [comment]
same issue here. though for me, it also comes with a "shadow buffer full" error, which is absurd because that's an EEVEE next error when I'm using cycles
