### ISSUE TITLE
[Linux]Can't import models

### ISSUE THREAD

**Issue by Kamyk141** [REDxEYE/SourceIO#336]
`Python:`` Traceback (most recent call last):
  File "/home/user/.config/blender/4.3/scripts/addons/SourceIO/blender_bindings/operators/source1_operators.py", line 52, in execute
    with FileBuffer(mdl_path) as f:
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.config/blender/4.3/scripts/addons/SourceIO/library/utils/file_utils.py", line 323, in __init__
    io.FileIO.__init__(self, file, mode, closefd, opener)
FileNotFoundError: [Errno 2] No such file or directory: ``TinyPath("/home/user/Pobrane/models_d88396d1-6a3f-4662-a91a-1e075ea44aee/models/ugc/76561197995159516/mickyan/weapons/357hds.mdl")`

yeah I'm using linux and can't import models, I can open xps with addon, but can't open source models so I assume it's this addon issue(?)

**Comment by REDxEYE** [comment]
Can you check that the file actually exist there? As you can see it complains about file not existing there

**Comment by Kamyk141** [comment]
![image1](https://github.com/user-attachments/assets/a778fbcb-f64f-473a-9f58-9ed4dccf5886)
everything needed to import the model is here

**Comment by REDxEYE** [comment]
I honestly dont have any clues. It failed on standart python file open call.

**Comment by Kamyk141** [comment]
that's weird because I can open everything normally except when trying to import something with this addon
I guess I'll just try to test some more

**Comment by REDxEYE** [comment]
SourceIO internally converts all paths to unix format

**Comment by REDxEYE** [comment]
Hm, i'll take a look

**Comment by REDxEYE** [comment]
Can you try to use version from master? I've added automatic conversion very recently, so you may have version without conversion

**Comment by Kamyk141** [comment]
![image](https://github.com/user-attachments/assets/6fbd6244-83e6-4282-9dee-8b1c6508d528)
well error is a bit different but it still tries to look for a file with /

**Comment by REDxEYE** [comment]
Can you call `file <path it tries to lookup>` and see if your system resolved it correctly?
Because your file explorer can render separators however it want

**Comment by Kamyk141** [comment]
![image](https://github.com/user-attachments/assets/99299584-e276-4623-9749-8a11e453b89c)
also full file name is here 
where when files were \ it was cut when importing only to hk_usp_45.mdl

**Comment by Kamyk141** [comment]
![image](https://github.com/user-attachments/assets/29b8c321-4194-4d5c-98a4-839f14794c4d)
that's everything

**Comment by REDxEYE** [comment]
Huh? I didnt print any mounted folders, did you check the `mount discovered` in import window?

**Comment by Kamyk141** [comment]
Yeah I always leave it checked
![image](https://github.com/user-attachments/assets/0af0a1a5-d8a9-4192-8d75-a03cc4e54ca6)
and here folder is mounted

**Comment by REDxEYE** [comment]
Are the materials available in paths it's trying to find them? On your screenshot i see all of the vmt/vtf files are in the same folder as mdl(it does not work like that)

**Comment by Kamyk141** [comment]
yeah I always used it like that
I just get models from steam workshop downloader because no reason to keep sfm installed just to download models
so back when I used windows the addon always worked perfectly when using it like that
just on linux it breaks
and on windows it worked nicely, everything imported perfectly and all
well I guess you can try it on your pc like that and see it works from steam workshop downloader and everything mounts correctly
just linux has a problem 
weird

**Comment by REDxEYE** [comment]
SourceIO does not support loading files from same folder as MDL, it wont even look there as it's not an path where it expects to find them

**Comment by Kamyk141** [comment]
well it did work on windows apparently lol
I guess I'll try to move files to correct paths and see if it imports correctly

**Comment by Kamyk141** [comment]
well it was easier for people who moved from sfm to blender and they don't use sfm at all, especially when models exist only for sfm and not blender

![image](https://github.com/user-attachments/assets/788b3071-f018-4aae-82dd-c4ad816041de)
welp
still broken
despite creating folders and moving files where they should be

**Comment by REDxEYE** [comment]
Potentially case sensitive file system issue. I'll try to add some sort of fix for that in later versions

**Comment by Kamyk141** [comment]
yay 
thank you <3

**Comment by REDxEYE** [comment]
I've added some additional path resolution thing to SourceIO, give it a try

**Comment by Kamyk141** [comment]
![image](https://github.com/user-attachments/assets/84f77ecf-2e37-4b69-87db-55346a5f7a0b)
now it tries to look for models folder but folder is here, weird

**Comment by REDxEYE** [comment]
You forgot `models` here
![image](https://github.com/user-attachments/assets/3a53164a-ebd2-452f-b04c-9a1fda1742c9)

**Comment by Kamyk141** [comment]
it's on the bottom
![image](https://github.com/user-attachments/assets/a7c7bd05-8001-4690-91c9-7af131274890)
that's when I collapse folders (not show what's inside them > thing next to folder icon

**Comment by REDxEYE** [comment]
You didnt get what i meant. `materials/models/bha-blah`

**Comment by Kamyk141** [comment]
![image](https://github.com/user-attachments/assets/f611fd79-3f6f-4e92-972e-962db4a7d195)
well now no materials here >~<

**Comment by REDxEYE** [comment]
![image](https://github.com/user-attachments/assets/7faf2d4d-e8a2-4b69-8583-e3c2ae94c7c5)
I still dont see models folder between materials and choev

**Comment by Kamyk141** [comment]
![image](https://github.com/user-attachments/assets/92eff03d-0fe5-4bf5-b520-09183accfb38)
it is here

**Comment by REDxEYE** [comment]
FFS, it should be `materials/models/choev/weapons/....`
And mdl and other mdl related files should be in `models/choev/weapons`

**Comment by Kamyk141** [comment]
I'll just get sfm and import it from there I guess

**Comment by REDxEYE** [comment]
Best way to do it. Since you cant unpack everything correctly let SFM do it

**Comment by Kamyk141** [comment]
![image](https://github.com/user-attachments/assets/9d8458ad-be7f-4c2d-a39e-17a5c5c2fa70)
I didn't install any workshop models 
I tried to import model that comes with sfm

**Comment by LoveRenamon** [comment]
I think you should close this, as this is not an SourceIO issue, but ZIP file not compiling with 2018 zip standards which will break compatibility with Amiga and UNIX standards. Theres nothing much RED can do as you.
https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT

you can work around by this by `cd` at addon path and use such bash script: ```sh
for file in *\\*
do
  target="${file//\\//}"
  mkdir -p "${target%/*}"
  mv -v "$file" "$target"
done
```

this should make the folders with the right names by expand `${file}` substring by replace the `\` with `/`, store that string inside `${target}`, then `mkdir -p` which create the whole path for you.
so you can't make the mistake as you're doing by place `models` MDL files inside the `materials`

**Comment by Kamyk141** [comment]
oh okay thank you, I thought it was addon issue sorry
