### ISSUE TITLE
Can't import SteamVR maps

### ISSUE THREAD

**Issue by techsideofficial** [REDxEYE/SourceIO#337]
![image](https://github.com/user-attachments/assets/7c2a9d6e-20a9-494d-9c97-914aea48d85b)

**Comment by REDxEYE** [comment]
Please upload sample file

**Comment by techsideofficial** [comment]
@REDxEYE 

[https://drive.google.com/drive/folders/1HfRIsUa87uvBMhE3noNLotWdL1AI53-_?usp=sharing](https://drive.google.com/drive/folders/1HfRIsUa87uvBMhE3noNLotWdL1AI53-_?usp=sharing)

**Comment by techsideofficial** [comment]
@REDxEYE 
How was it fixed?

**Comment by REDxEYE** [comment]
You can check the commit

**Comment by techsideofficial** [comment]
@REDxEYE I installed it but it's throwing different errors
![image](https://github.com/user-attachments/assets/4a1f277a-9373-4353-9786-53b9d47d8085)

**Comment by REDxEYE** [comment]
Try to fully remove and re-install from scratch
disable addon, restart blender and then delete

**Comment by techsideofficial** [comment]
![image](https://github.com/user-attachments/assets/dc0d3549-27ef-421f-8edd-ea9aaf0d5516)

**Comment by REDxEYE** [comment]
Have you restarted blender?

**Comment by techsideofficial** [comment]
yes

**Comment by techsideofficial** [comment]
![image](https://github.com/user-attachments/assets/a3e49a56-38e3-4405-bbf5-8434dfd72716)

**Comment by REDxEYE** [comment]
This means that the VPK file you tried to open does not exist

**Comment by REDxEYE** [comment]
I'll look into it

**Comment by techsideofficial** [comment]
Here's the SteamVR addon if that helps: 

[https://steamcommunity.com/sharedfiles/filedetails/?id=928184711&searchtext=turret](https://steamcommunity.com/sharedfiles/filedetails/?id=928184711&searchtext=turret)
