### ISSUE TITLE
4.3.2 blender update breaks addon

### ISSUE THREAD

**Issue by SomeRandomGuy852** [REDxEYE/SourceIO#348]
Ok. So whenever i try to import a .mdl file, this happens (yes, i downloaded the latest release)
![Screenshot 2024-12-22 174601](https://github.com/user-attachments/assets/89d497fc-6edb-479d-9126-a6ba4464c089)
Is there a fix to this?

**Comment by REDxEYE** [comment]
Blender 4.3 is only supported in master branch, latest release only support 4.2 and lower

**Comment by SomeRandomGuy852** [comment]
> Blender 4.3 is only supported in master branch, latest release only support 4.2 and lower

Ohh. Thanks!
