### ISSUE TITLE
Would like to participate

### ISSUE THREAD

**Issue by Kllngii** [REDxEYE/SourceIO#35]
Hi,
I would like to compile some files to add macOS support. Would you be so kind to tell me, which libraries/modules you compiled to the PySourceIOUtils.so/PySourceIOUtils.pyd archive? 

I already compiled the VTFLib13 for macos and the PySourceIOUtils is the only thing missing to successfully run SourceIO on macOS.

**Comment by REDxEYE** [comment]
Source code for PySourceIOUtils will be uploaded to github really soon, i only need to clean it up and re-sub-module everything

**Comment by Kllngii** [comment]
Thank you! I would really like to help.

**Comment by REDxEYE** [comment]
@Kllngii Here you go https://github.com/REDxEYE/SourceIO_Source2Utils
