### ISSUE TITLE
new mdl importer isn't working

### ISSUE THREAD

**Issue by loliXn** [REDxEYE/SourceIO#37]
pretty much self-explainatory, old version of the addon (3.75) was working fine, but maybe I'm doing something wrong here. (blender 2.83.16 build, used the old version on this build too)
![image](https://user-images.githubusercontent.com/20803376/83585396-6c3c1680-a552-11ea-8300-eb783e3d6c78.png)

**Comment by REDxEYE** [comment]
That's import error, easy to fix

**Comment by REDxEYE** [comment]
Should be fixed now

**Comment by loliXn** [comment]
tried to reinstall but unfortunately it doesn't seem to work for me. i'll try to install the old version just to check if it's something the matter on my side. 
![image](https://user-images.githubusercontent.com/20803376/83642384-72b0a980-a5b7-11ea-8053-d3364b96beed.png)

**Comment by loliXn** [comment]
yeah, the 3.75 addon (downloaded on may 22) seems to be working just fine, even the experimental import mode was checked. just in case, i was trying to import the same model on both versions.

also, instead of creating another issue, i wanted to tell about one small bug which gives some kind of error in the bottom line of blender when i'm deleting something.
![image](https://user-images.githubusercontent.com/20803376/83643993-6c233180-a5b9-11ea-952d-ff1c0093397f.png)

**Comment by REDxEYE** [comment]
Should be fixed now
