### ISSUE TITLE
VMT import/export

### ISSUE THREAD

**Issue by SupinePandora43** [REDxEYE/SourceIO#38]

**Comment by REDxEYE** [comment]
Hm, might do that in future updates

**Comment by Xephobia** [comment]
> 
> 
> Hm, might do that in future updates

someone has done a vmt parser https://github.com/lasa01/vmfpy

**Comment by REDxEYE** [comment]
I use Valve own parser

**Comment by REDxEYE** [comment]
https://github.com/REDxEYE/SourceIO/blob/master/utilities/valve_utils.py#L350

**Comment by SupinePandora43** [comment]
:thinking:

**Comment by REDxEYE** [comment]
vmt import is back again

**Comment by SupinePandora43** [comment]
lol

**Comment by SupinePandora43** [comment]
lol
