### ISSUE TITLE
Eye Texture - UV mapping

### ISSUE THREAD

**Issue by Gnates** [REDxEYE/SourceIO#4]
**Blender 2.80 Beta** [ Date: **2019-03-17** Hash: **9099305771ec** ]
SourceIO v**3.4.0**
SFM Model: http://sfmlab.com/item/3383/

Someone was having issues with eye textures not applying correctly in Blender:
- http://i68.tinypic.com/262b53r.jpg
I don't know which blender build or add-on version he is using, but I was able to replicate the problem from his screenshot. 

It's similar to what I've experienced before with other models (Harley Quinn), but this time it's different.
Before, I usually change the scales on the mapping node (https://docs.blender.org/manual/en/dev/_images/render_blender-render_materials_nodes_types_vector_mapping_node.png) to quickly fix the issue, but this particular model may require more tweaking.

**Comment by REDxEYE** [comment]
This model probably uses Source engine "eyerefract" shader, it doesn't need UV map to work

**Comment by Gnates** [comment]
For Blender users who wish to do renders within Blender, what's the recommended method to fix the eyes?

**Comment by Dark-trial** [comment]
Any solution?
