### ISSUE TITLE
polygons not connected

### ISSUE THREAD

**Issue by SupinePandora43** [REDxEYE/SourceIO#42]
![image](https://user-images.githubusercontent.com/36124472/85928710-6f63c180-b8c8-11ea-9ede-6b889d5bf70c.png)
// when importing mdl

**Comment by REDxEYE** [comment]
This is supposed to be like that on this model

**Comment by SupinePandora43** [comment]
@REDxEYE  when i import via blender source tools it normal

**Comment by REDxEYE** [comment]
BST might does some vertex merging.
My plugin import geometry as it is in mdl file

**Comment by SupinePandora43** [comment]
oof

**Comment by REDxEYE** [comment]
Just use vertex merge in blender
