### ISSUE TITLE
Error When Importing (+ Another Small Error)

### ISSUE THREAD

**Issue by MLSp3nce** [REDxEYE/SourceIO#43]
![image](https://user-images.githubusercontent.com/57275043/86295824-73902780-bbc5-11ea-81e8-bca343312170.png)
Im not sure how I could explain this, also another error I have found is when you import any model, the meshes are not parented to the armature and only connected using the modifier, and also bodygroups are not in collections and such but yeah, the error I wanted to talk about was this error which im unsure how it happened.

**Comment by REDxEYE** [comment]
Most of things you're talking about were removed in new MDL import module

**Comment by REDxEYE** [comment]
About error on screenshots. This assertions are placed here to prevent blender crash
I need to examine this model, can you upload it?

**Comment by MLSp3nce** [comment]
The model used was this:
https://steamcommunity.com/sharedfiles/filedetails/?id=1723457636&searchtext=

**Comment by REDxEYE** [comment]
Should be fixed now
