### ISSUE TITLE
Feature Request: Import Collision Model

### ISSUE THREAD

**Issue by SethTooQuick** [REDxEYE/SourceIO#44]
It'd be cool if when importing MDLs if you could enable an option to also import the collision model.

**Comment by REDxEYE** [comment]
Working on it

**Comment by SethTooQuick** [comment]
Dope

**Comment by REDxEYE** [comment]
It's not yet finished, i connot get meshes into correct orientation

**Comment by REDxEYE** [comment]
Proper collision import not possibe, because SourceIO cannot parse MDL animations. Weird i know, but animations are used for shape position/rotation calculation
