### ISSUE TITLE
Error when importing model in Blender 2.90

### ISSUE THREAD

**Issue by MLSp3nce** [REDxEYE/SourceIO#45]
![image](https://user-images.githubusercontent.com/57275043/87072318-87e9ab00-c1e9-11ea-896b-ab48557da657.png)

model used: https://steamcommunity.com/workshop/browse/?appid=1840&searchtext=Vanny&childpublishedfileid=0&browsesort=mostrecent&section=readytouseitems

**Comment by REDxEYE** [comment]
There multiple models, can you provide direct link to model?

**Comment by MLSp3nce** [comment]
my bad for responding super late, it is this one https://steamcommunity.com/sharedfiles/filedetails/?id=2147037116&searchtext=Vanny

**Comment by REDxEYE** [comment]
try updating addon, model parsed fine for me, no errors
