### ISSUE TITLE
Import texture ?

### ISSUE THREAD

**Issue by Xiarno** [REDxEYE/SourceIO#46]
Upon searching the web, I've stumbled upon this tweet: https://twitter.com/DaLoaf1/status/1282757020022640642
It mention an ability to import texture & possibly other things in the screenshot.

In the comment, an user requested to know which addon it was, and the OP answered with a link directing to this addon. After installation and trials, I did not manage to make any of the option shown in the screenshot available and usable. The only option I was able to get is "Write QC".

How does this user get the ability/options shown in the screenshot and how to activate them to be used ?
Thanks !

**Comment by REDxEYE** [comment]
Different version of plugin, texture import will be back in future versions

**Comment by Xiarno** [comment]
> Different version of plugin, texture import will be back in future versions

Is it possible to get the version used ?
Does the addon auto-update or do I need to manually download it here each time an update is done ?

**Comment by REDxEYE** [comment]
texture import was never fully finished, it's better to wait for new version.
Also, mdl loader in old version was crappy, in newer versions it's 10 times better

**Comment by Xiarno** [comment]
> texture import was never fully finished, it's better to wait for new version.
> Also, mdl loader in old version was crappy, in newer versions it's 10 times better

Mind asking when approx the newer version will be released ?
Also, will manually downloading & installing be necessary to update or will it auto-update ?

**Comment by REDxEYE** [comment]
Brought back mdl texture auto-import and VMT import.
No, there is no auto-update

**Comment by Xiarno** [comment]
> Brought back mdl texture auto-import and VMT import.
> No, there is no auto-update

Okay then. So I guess I need to check from time to time, download it again and update it then ? :/

**Comment by REDxEYE** [comment]
Yes
