### ISSUE TITLE
Bone orientation on vmdl is inverted on model's right side.

### ISSUE THREAD

**Issue by Ruuubickk** [REDxEYE/SourceIO#47]
As shown in the image below, when a model is imported, the bones are facing the wrong direction on the right side of the armature

[aghanim_model.zip](https://github.com/REDxEYE/SourceIO/files/4928035/aghanim_model.zip)

![blender_NZx5hUIWSh](https://user-images.githubusercontent.com/44787492/87597389-023a9380-c6f2-11ea-9198-13b56b5a27b3.png)

**Comment by REDxEYE** [comment]
This is how Source spaghetti compiler does it's stuff, connot do much about that
