### ISSUE TITLE
Import error: L4D2 survivor model meshes are messed up

### ISSUE THREAD

**Issue by ZeqMacaw** [REDxEYE/SourceIO#5]
In version 3.4.0: 
Importing Left 4 Dead 2 pak01_dir.vpk "models\survivors\survivor_mechanic.mdl" shows Ellis with much of the mesh messed up.
Importing Left 4 Dead 2 pak01_dir.vpk "models\survivors\survivor_coach.mdl" shows Coach with much of the mesh messed up.

(Importing Left 4 Dead 2 pak01_dir.vpk "models\v_models\v_desert_eagle.mdl" shows as expected.)

**Comment by REDxEYE** [comment]
Known bug, dunno how to fix. Might be something with fixups

**Comment by REDxEYE** [comment]
Should be fixed now
