### ISSUE TITLE
Materials not properly applied to imported maps

### ISSUE THREAD

**Issue by 107zxz** [REDxEYE/SourceIO#54]
When importing a map, the first material in the list of imported materials is applied to every surface in the map, as can be seen below. I have tested this by selecting assigned faces for each material in edit mode, which confirmed this.
![image](https://user-images.githubusercontent.com/55370376/90305630-ca4a8a00-df03-11ea-9387-dfc3cbdb05c5.png)

**Comment by REDxEYE** [comment]
BSP import feature is WIP and does not work properly yet
