### ISSUE TITLE
Bodygroups not sorted anymore/Objects not parented to Armature

### ISSUE THREAD

**Issue by MLSp3nce** [REDxEYE/SourceIO#55]
So i know I always come on here and I've seen this issue for a long time now, but I didn't know if it were intentional or not so i decided to write it on here. Whenever a model is imported, it is no longer parented to its armature so whenever you move it in object mode, it doesnt move the meshes. The other issue is that the bodygroups are no longer sorted in collections like they were with the previous importer. Do you have plans to bring back the bodygroups feature and fix the issue?

**Comment by REDxEYE** [comment]
armature parenting was brought back recently

**Comment by MLSp3nce** [comment]
Yes, im aware of that, there is still the other half of this comment i wrote though about the bodygroups. thanks again for all the changes you've made!
