### ISSUE TITLE
Dota2 Imports

### ISSUE THREAD

**Issue by PteJack** [REDxEYE/SourceIO#58]
Hey REDxEYE.  
I'm in the process of including SourceIO as an Source2 importer with a "watch the development of this tools as a Blender Source Tools alternative" (I'm not quite ready to highlight it yet as it is still in development) in the new guide I'm writing for converting models for use in SFM using Blender 2.8x and up. 
I'm running into issues with Source2 imports.  Half-Life: Alyx models seem to be importing well and the the VMat_C imports are creating the shader nodes and texturing the models very well, however all I'm getting for Dota2 imports are base armatures.  

I've tried both the Latest Release 3.7.11 and the SourceIO Master (3.8.0 as of today) and get the same result.  Models start to Import, then the add-on is bailing as soon as it hits the vmesh_c file.  

This is the import log written to the console. 
``register_class(...):
Warning: 'source_io.utils' doesn't contain '_PT_' with prefix & suffix
Loading 0/1
{'models/courier/badger/asset_sequences_76def6bf.vagrp': WindowsPath('G:/DNS-323/DOTA/models/courier/badger/asset_sequences_76def6bf.vagrp_c'),
 'models/courier/badger/courier_badger_05f497f2.vagrp': WindowsPath('G:/DNS-323/DOTA/models/courier/badger/courier_badger_05f497f2.vagrp_c'),
 'models/courier/badger/courier_badger_model.vmesh': WindowsPath('G:/DNS-323/DOTA/models/courier/badger/courier_badger_model.vmesh_c')}
``
And this is all I get for a model, (and it doesn't matter what DOTA2 model I try to import, all I get is an armature and a bail out at the vmesh_c)
![2020-10-02_0-30-17](https://user-images.githubusercontent.com/58664549/94894562-dbfdd780-0446-11eb-825c-5261cc4b4021.png)

I thought this tool was supposed to be DOTA2 compatible.  

Then again, I'm also wondering if this might be because I'm using Blender 2.9.1(Alpha) (I'm trying to keep the guide ahead of the development of Blender as well) and the tool is breaking because of that. Am I finding an upcoming bug you might have to address and soon.

So the question becomes, in the current version of Blender (2.9.0.1) is the tool Dota2 compatible? If it is supposed to be, you may have a problem when 2.9.1 hits the market.

Further issues I've noticed. When importing VMat_c.  If a texture can't be found, the add-on start looking for it. I like this idea, however, when I found it starts looking in the Root of the drive I'm using, I become concerned over security issues. 
The test I performed was to move a VTEX_C file to various places on my computer and then import the VMAT_C. I find that the search doesn't extend beyond the drive the vmat_c is in, but... 
In one test, I moved the vtex_c from my extractfolder\models\materials folder into my C:\ root folder and imported the vmat_c. When I viewed the log and found the only reason it didn't convert the texture to a TGA and load it into the image texture node was because it didn't have permission to write to the folder the vtex_c was in (the C:\ (Root) or my C:\Users folder) I have to ask, to what extent does your add-on search drives for missing content and what is it fetching? Are you gathering information about me? Is the add-on sending you stuff it finds? (you know, the old paranoia thing... LOL)  Maybe limiting the search to the extract folder would be better (if you can??).  For example if I extract a VPK to a folder called HL_Alyx on my desktop, the search can access up to the point that if finds the models and materials main folders but not outside the extraction folder. Kind of a hard thing to code around, but the add-on should not be searching system folders.  

Next issue I have is import VTMs with separated Alpha. This seems to be hit and miss.  For example For some VMTs I get the RGB and the A textures, but here, (this is the bot_worker_a_red VTF from TF2), when I imported the VTF with the Separate Alpha box enabled, as you can see in this picture all I get is a RGB texture. On the right is that texture's Alpha channel shown in VTFEdit. The Alpha channel in this texture is not separated and it is not written as an Alpha texture by the add-on.
![2020-10-02_0-54-03](https://user-images.githubusercontent.com/58664549/94896310-6d227d80-044a-11eb-917f-117cc78d199e.png)

The last issue I have for now in 3.7.11, (but I think you've already fixed in the 3.8.0 master for your next release), is that when using the  import vtex_c files. It failed every time I tried to use it in 3.7.11, I think it was because the Separate Alpha check box was missing from the Options in the import browser screen (the check box is now present in the screen in the new 3.8.0 master.)

One last thing, the Import Source2 vwrld map files.  Scanning the vpks for both Dota2 and HL:Alyxx I can't find a single vwrld type file. Is this something that is exported from the game's workshop tools like the vmf files used by Hammer for the Source engine?  

I must really congratulate you on how you're pulling your Shapekey names and populating them in Blender. I only wish that Crowbar or Blender Source Tools would do the same.  There isn't a single corrective shape name that breaches the Blender 65 character limit and is truncated when I import a HWM model.  Great job there! 

I do have other issues with the way things are brought in, but those I mentioned are at the top of my list. 

Your doing a fantastic job with this tool and it is a far scream from where it was when I first started watching the development. I only wish I had your programming skill and the Valve Model knowledge you do to create an add-on like this. 

Regards, Pte Jack!

Oh, on closing, another "simply cosmetic" thing you you might want to check is on some of your "Import" buttons, what are the label names they're using (wink-wink, nudge-nudge, chuckle)

**Comment by REDxEYE** [comment]
About file searching. SourceIO just tries every possible path from combination of addon_path and file_path, nothing more.
https://github.com/REDxEYE/SourceIO/blob/44b68319d4782dd1340b83f166640718818dbb34/utilities/path_utilities.py#L26

**Comment by REDxEYE** [comment]
About dota2 support.
Addon do have Dota2 support, but one of latest update broke everything again. I might fix the issue, but i need updated model files from dota2 as i don't have it installed

**Comment by REDxEYE** [comment]
About shape key names. I'm truncating them and putting original name into blender text file 
https://github.com/REDxEYE/SourceIO/blob/44b68319d4782dd1340b83f166640718818dbb34/source2/resouce_types/valve_model.py#L120

**Comment by PteJack** [comment]
def backwalk_file_resolver(current_path, file_to_find): Ah, so that's why it finds

**Comment by rakaharda** [comment]
Hi.
Do you still need the models?
