### ISSUE TITLE
Broken shape keys

### ISSUE THREAD

**Issue by HealingWind1997** [REDxEYE/SourceIO#59]
https://sfmlab.com/project/30339/

This model here seems to break when imported via MDL. It works fine when using Crowbar and decompiling, but usually MDL importing provides stronger and more accurate rips of SFM models. I'm not an SFM expert, so I'm not sure if there is something specific in this model compared to others by this model maker that causes this issue.

**Comment by REDxEYE** [comment]
Should be fixed in the latest release
