### ISSUE TITLE
Import error: "Normalize bones" breaks rigging on some models

### ISSUE THREAD

**Issue by Irastris** [REDxEYE/SourceIO#6]
Currently using v3.4.0 as this is the latest working in Blender 2.8 as of nightly 009dbc2bc9fb.

Normalize bones was stated as having no affect on rigging, yet breaks the weighting of certain models when enabled.

As I currently do not know GitHub's stance on NSFW imagery in public issues, I will withhold sharing image examples for now, but the problem can be examined via StealthClobber's MercyNude2018-SFM-WIP-V2 model.

**Comment by REDxEYE** [comment]
Known issue, some bones become 0 lenght and blender removes them. Fix will be implemented as soon as i figure out how to deal with it

**Comment by REDxEYE** [comment]
Should be fixed now
