### ISSUE TITLE
Cannot import session file (.dmx)

### ISSUE THREAD

**Issue by Xiarno** [REDxEYE/SourceIO#60]
Always the same error, whatever the session I try
I have the latest release (3.7.11). Blender version is 2.90.1. Windows 10.
I also wanted to try the master version, but apparently there is no import dmx function in the master.
![image](https://user-images.githubusercontent.com/24660485/99730780-02291680-2a8b-11eb-9030-701309b8f315.png)

**Comment by REDxEYE** [comment]
dmx import is WIP feature and not currently usable
