### ISSUE TITLE
NotImplementedError - Can't Enable Addon

### ISSUE THREAD

**Issue by lcrud** [REDxEYE/SourceIO#61]
Hi everyone. Love this tool for my Windows setup, however it seems I'm having issues installing the addon on my Mac version. of Blender (2.90.1). Getting the error in the image below when trying to install latest stable version of SourceIO.  Any tips?

  <a href="https://ibb.co/vsXCLDR"><img src="https://i.ibb.co/PTDs1t0/Screen-Shot-2020-11-21-at-10-43-24-AM.png" alt="Screen-Shot-2020-11-21-at-10-43-24-AM" border="0" /></a>

**Comment by REDxEYE** [comment]
Texture import is not supported on Mac

**Comment by lcrud** [comment]
got it - thanks for speedy reply. 
i'll use my windows set up to start my sessions then open those save files on mac.  hopefully a native solution for mac in the future!  
Drooling over the M1 chip models but they don't support bootcamp right now :(
