### ISSUE TITLE
VTF Import error

### ISSUE THREAD

**Issue by MLSp3nce** [REDxEYE/SourceIO#64]
for every vtf import I do, i end up getting this error:
![image](https://user-images.githubusercontent.com/57275043/102017384-b0e01000-3d34-11eb-80fd-21206c4addbb.png)

Blender version used: Blender 2.92.0 Alpha

**Comment by Xiarno** [comment]
I can confirm that I'm also getting this error on 2.90.1.

**Comment by REDxEYE** [comment]
Fixed in one of recent commits
