### ISSUE TITLE
trying to combine textures just errors

### ISSUE THREAD

**Issue by arceuss** [REDxEYE/SourceIO#70]
![image](https://user-images.githubusercontent.com/28229451/103185106-3062f880-4878-11eb-9b5a-ab75ca930342.png)

**Comment by arceuss** [comment]
are the textures saved anywhere or something

**Comment by REDxEYE** [comment]
Should be fixed now

**Comment by REDxEYE** [comment]
This is not SourceIO error, report this bug to `material-combiner-addon` developer
