### ISSUE TITLE
Skybox cubemap texture

### ISSUE THREAD

**Issue by ShadelessFox** [REDxEYE/SourceIO#73]
Currently skyboxes are displayed as brush with `tools/toolsskybox` material. We can delete these brushes and render sky as world node in blender.

**Comment by syborg64** [comment]
wouldn't this break maps that are discontinuous, where several layers are stacked or when more generally stuff is hidden behind the skybox brushes ?

**Comment by ShadelessFox** [comment]
It may :)

**Comment by REDxEYE** [comment]
Implemented in https://github.com/REDxEYE/SourceIO/releases/tag/3.15.5
