### ISSUE TITLE
Textures Not Exporting from MDLs

### ISSUE THREAD

**Issue by higgy999** [REDxEYE/SourceIO#75]
I'm trying to get the Scout's Scattergun into Unity and found this addon. Currently, the model imports fine with the VTFs and VMTs automatically which I thought was very cool. But when exporting to GLTF or FBX and putting them in Unity or back into Blender, it will be missing textures. I thought this was an issue with FBX not supporting shader graph exports but when putting it back into Blender the graph is still there (although it is missing some nodes). But it is referencing the textures correctly though. Here is a comparison of the shader graphs: 
.Blend
![Blend](https://user-images.githubusercontent.com/12685323/104827700-a8e12780-582e-11eb-82d7-21700c715835.png)
.FBX
![FBX](https://user-images.githubusercontent.com/12685323/104827728-ff4e6600-582e-11eb-9552-b480af5ec295.png)
Unity just says the material is missing.

**Comment by REDxEYE** [comment]
That probably not SourceIO issue, but I suggest you unpack textures before exporting to FBX or any other format

**Comment by higgy999** [comment]
I fixed it. You have to tell Blender to save textures when necessary (button next to the X by the name of the texture).
