### ISSUE TITLE
SourceIO No longer working with Blender 2.93

### ISSUE THREAD

**Issue by MLSp3nce** [REDxEYE/SourceIO#77]
![image](https://user-images.githubusercontent.com/57275043/107980508-670ee280-6f8e-11eb-840c-e359413f82b3.png)

I don't have much to say aside from this screenshot as the title explains it all.

**Comment by REDxEYE** [comment]
looks like they updated the version of python, I need to recompile this library

**Comment by Irmitya** [comment]
Are you waiting for 2.93 to enter beta or whatever to fix?

**Comment by REDxEYE** [comment]
If I fix it right now, I will break addon for blender 2.80-2.92 users

**Comment by Irmitya** [comment]
You could include two files and do a blender version check to only use the old version if the blender version is old. 
You could also create a branch with the new/old files, or just include a separate file not committed to any branches, allowing people like us to manually install the patch/fix. 

The new python change isn't going to be reverted, meaning everyone using later 2.93 versions and afterwards, will be permanently locked off, having to use older versions for the sole purpose of using this one addon (and the addons using a certain kind of 2.7 compatibility setup). 

- - - - - 
A thing I was going to include in this post was that "I'd be willing to compile it myself if I had the necessary files". 
I then noticed this is only a "functional" issue for SFM2 and that 
1) I don't have any files for that, and 
2) I edited the addon to bypass/ignore the errors, meaning I don't "personally" need a fix. 

You should either include a working version "somewhere" for new Blender, or at least create bypass code that disables SFM2, for people not able to do so themselves.

**Comment by REDxEYE** [comment]
https://github.com/REDxEYE/SourceIO/releases/tag/3.11.2-3.9

**Comment by theoldben** [comment]
I would not call this a bug, but I do get a permissions error trying to install SourceIO on Blender 2.93, Win 10.
Would you happen to know what folder needs access permissions or if I have to run Blender in Admin Mode or something?


```
location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "E:\Blender\stable\blender-windows64\2.93\scripts\startup\bl_operators\userpref.py", line 767, in execute
    shutil.rmtree(path)
  File "E:\Blender\stable\blender-windows64\2.93\python\lib\shutil.py", line 740, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "E:\Blender\stable\blender-windows64\2.93\python\lib\shutil.py", line 613, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "E:\Blender\stable\blender-windows64\2.93\python\lib\shutil.py", line 613, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "E:\Blender\stable\blender-windows64\2.93\python\lib\shutil.py", line 618, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "E:\Blender\stable\blender-windows64\2.93\python\lib\shutil.py", line 616, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\Admin\\AppData\\Roaming\\Blender Foundation\\Blender\\2.93\\scripts\\addons\\SourceIO\\vtf\\VTFWrapper\\VTFLib.x64.dll'

location: <unknown location>:-1
```

Seems to be related to this: https://developer.blender.org/T77837

**Comment by REDxEYE** [comment]
Addon can be removed without errors if you first disable it and then restart the blender
This way addon can be uninstalled without error

**Comment by theoldben** [comment]
Can confirm! Works perfectly, both for un- and reinstalling.
