### ISSUE TITLE
Support to xbox 360 big endian

### ISSUE THREAD

**Issue by metalex10** [REDxEYE/SourceIO#78]
is possible add Support to xbox 360 big endian
-Export bsp to big endian?
for example import l4d maps pc little endian to blender and export to x360

studiomdl is document for mdl

and 

https://github.com/metalex10/SourceEngine2007/blob/master/src_main/utils/xbox/MakeGameData/MakeMaps.cpp

**Comment by REDxEYE** [comment]
Please provide a file example

**Comment by REDxEYE** [comment]
closed due to inactivity
