### ISSUE TITLE
Could mdl version 44 be supported?

### ISSUE THREAD

**Issue by asd417** [REDxEYE/SourceIO#8]
mdl version 44 used for tf2 is not currently supported. Could it be added as well?

**Comment by REDxEYE** [comment]
All models in TF2 are V48

**Comment by asd417** [comment]
I tested with several old props (props from 2fort) and all of the ones I tested were version 44. Backward compatibility would be nice.

**Comment by REDxEYE** [comment]
Should work now

**Comment by REDxEYE** [comment]
Test it
