### ISSUE TITLE
Addon Does not remove cleanly

### ISSUE THREAD

**Issue by PteJack** [REDxEYE/SourceIO#80]
Hey Team, just a note for consideration.

When there is a new version of an add-on, before I install the new version I usually try the remove button on the old version to remove it so the new version installs cleanly.

THe previous version I had of Source_IO was 3.8.x and I just downloaded 3.9.3. This is what was left over when I used the Remove button in the add-on.  
![2021-02-27_13-16-22](https://user-images.githubusercontent.com/58664549/109399208-b34b1280-78fe-11eb-92e3-7111b05fb043.png)

In order to do the clean install, I have to manually delete the AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\SourceIO Folder. 
 
Would you consider fixing this for future releases?

Thanks

PteJack

**Comment by REDxEYE** [comment]
Known issue, no way to fix, sorry
