### ISSUE TITLE
KeyError: 'the length of IDProperty names is limited to 63 characters'

### ISSUE THREAD

**Issue by greenunknown** [REDxEYE/SourceIO#85]
I've run into an error trying to import a [SFM model](https://steamcommunity.com/sharedfiles/filedetails/?id=2182234248) into my Blender 2.91. I'm not sure if this is an issue with this addon or with the file itself but I have gotten other files from the workshop to work and have tried the length of the file path to no avail. If you need any more information, please let me know. Thanks!
![image](https://user-images.githubusercontent.com/12701414/111932249-46004c80-8a7a-11eb-96d9-64d10b13ad53.png)

The steps I took in blender to reproduce is "File > Import > Source Engine Assets > Source model".

**Comment by greenunknown** [comment]
Sorry for the inconvenience. It turns out restarting my system and changing the length again may have fixed it.

**Comment by Jmvars** [comment]
> 
> 
> Sorry for the inconvenience. It turns out restarting my system and changing the length again may have fixed it.

How did you change the length?

**Comment by REDxEYE** [comment]
It's impossible to change the max length of names in a blender, they are hardcoded to be char[64] buffers.

**Comment by greenunknown** [comment]
@Jmvars If I recall, it's been a while, the pathname was just too long for me so I shortened the path itself (i.e. moved the SFM models up higher in the directory since there were several layers of folders for the models I was using). I didn't change anything with Blender itself. Hopefully, that works for you.
