### ISSUE TITLE
hey, im that one guy that cares about s2fm.

### ISSUE THREAD

**Issue by okmrsavageYT** [REDxEYE/SourceIO#87]
If you can convert a dmx (session) to blender, then can you convert it to whatever s2fm uses? I know the dmx to blender isnt done yet but if it is possible then i dont see why dmx > blend > whatevers2fmuseslol

(i am now realizing that s2fm also uses dmx for sessions but they store more data?)

**Comment by REDxEYE** [comment]
S2FM uses slightly different scene layout, it's probably possible, but that's out of SourceIO scope

**Comment by okmrsavageYT** [comment]
¯\_(ツ)_/¯ i mean its not like i can complain this thing is pretty cool
