### ISSUE TITLE
Error when importing .bsp, "unpack requires a buffer of 4 bytes"

### ISSUE THREAD

**Issue by headassbtw** [REDxEYE/SourceIO#89]
I'm trying to import an extracted .bsp file (from titanfall 2 if that's of relevance to the issue) and i keep running across the error of `struct.error: unpack requires a buffer of 4 bytes` (I tried a different map and now it says 2 bytes, not sure what's going on.) I'm using blender 2.92, and the latest version of the plugin, downloaded from the repo (not releases.) Is this a fault of the plugin, or the modified engine that the game runs on?

edit: tested with an apex bsp, does the same thing

edit 2: trying to force myself to learn more python to try and fix it myself

edit 3: i gave up and i hate everything

**Comment by REDxEYE** [comment]
Titanfall 2 is unsupported

**Comment by REDxEYE** [comment]
Will be supported in future tho

**Comment by headassbtw** [comment]
ye, i figured that out shortly after doing that comment lol, read into it a lot more, and kinda feel stupid, but i'm really happy that it's planned though!
