### ISSUE TITLE
importing bsp map from sfm, has no texture with error

### ISSUE THREAD

**Issue by mlgpro720** [REDxEYE/SourceIO#90]
so its my first time using this 
and when i load a map with the import source map (bsp)

there was an error
i send an image of the error
in both console and log
![log1](https://user-images.githubusercontent.com/84569141/119119566-8158d080-ba55-11eb-83c9-eb8b433afae8.PNG)
![log2](https://user-images.githubusercontent.com/84569141/119118773-c0d2ed00-ba54-11eb-8656-814240bd1e31.PNG)

and after that error the map loads
but the material doesn't here is what i got
![log3](https://user-images.githubusercontent.com/84569141/119118974-efe95e80-ba54-11eb-95e8-1005d94ef72d.PNG)
and as you can see there is no texture
that and in the top right corner i have material preview on

idk how to fix this and im in need of using blender for my sfm projects

please help me
thank you

**Comment by REDxEYE** [comment]
Please, provide game name and map link

**Comment by mlgpro720** [comment]
The map i used is
https://sfmlab.com/project/28324

The game is sfm(sourcefilmmaker

**Comment by REDxEYE** [comment]
Fixed now, please test

**Comment by mlgpro720** [comment]
thank you very much!!

it works perfectly now
