### ISSUE TITLE
The version of the 2.93 don't get installed in Blender

### ISSUE THREAD

**Issue by 77pixelAZ** [REDxEYE/SourceIO#92]
**Take one look of this:** 
![Screenshot (636)](https://user-images.githubusercontent.com/62453528/121336489-db91d680-c91b-11eb-9381-03d59d2a1e1a.png)

**Comment by REDxEYE** [comment]
That's Blender source tools error
![image](https://user-images.githubusercontent.com/17544576/122284842-acb8c900-cef6-11eb-925a-2d83a754ef68.png)
Take a closer loot at this line

**Comment by REDxEYE** [comment]
This is repo for Blender source tools https://github.com/Artfunkel/BlenderSourceTools
