### ISSUE TITLE
Alyx animations broken?

### ISSUE THREAD

**Issue by TravisTouchdown-Offical** [REDxEYE/SourceIO#96]
![image](https://user-images.githubusercontent.com/82841262/123352506-70f0b580-d52d-11eb-9c98-6642d5ebc853.png)
Am I importing this wrong?

**Comment by TravisTouchdown-Offical** [comment]
![image](https://user-images.githubusercontent.com/82841262/123353412-75b66900-d52f-11eb-89a5-ad939e6050d5.png)

**Comment by REDxEYE** [comment]
Yes, Source2 animation import isn't finished
